### ISSUE TITLE
"Engine Error: File corruption detected. please repair or re-install the game"

### ISSUE THREAD

**Issue by Cali4niaX** [R2Northstar/Northstar#104]
Game gives File corruption message even after reinstalling the game entirly.
![error](https://user-images.githubusercontent.com/54128090/147864283-0d103c76-6c0a-4822-9a13-899773259292.PNG)

**Comment by SeamusMullan** [comment]
First suggestion, open vanilla titanfall 2, if that doesn't work, try repair your files in steam/origin.

Note: This is an engine error, usually not an error with northstar but with the default game. I don't think the devs will be able to fix this, but who knows!

**Comment by pyrowski5** [comment]
I have the same error. Vanilla works. Repairing and reinstalling did not help. I attached a log from the launch. The game crashes always at the same step
[nslog03-01-2022 02-07-25.txt](https://github.com/R2Northstar/Northstar/files/7800043/nslog03-01-2022.02-07-25.txt)

**Comment by GeckoEidechse** [comment]
Yeah it's a somewhat known problem that has different solutions for different people but it still doesn't work for some.

The TL;DR is that it stems from the interaction between Origin and `Titanfall2-unpacked.exe`.

Check the pinned issue #6.
