### ISSUE TITLE
Installing Northstar hasn't changed it

### ISSUE THREAD

**Issue by flynnito** [R2Northstar/Northstar#107]
After launching the NorthstarLauncher.exe file Titanfall starts up but the pop up meant to say thank you for installing Northstar does not appear. Instead it has the standard start up screen and under multiplier it just says contacting respawn servers constantly. Haven't seen this issue in any other threads or posts but if has been solved let me know and if not is there a solution.

Thank you.

**Comment by skittles9823** [comment]
Try running NorthstarLauncher as admin.

**Comment by GeckoEidechse** [comment]
In the main menu in game after launching Northstar, go to _Mods_ -> _Authentication Agreement_ and select _Yes_.

Then [follow the rest of the installation instructions](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup) and see if you can make it to the server browser and join a game.

**Comment by flynnito** [comment]
I tried running it on admin and that doesn't make a difference. I also
don't have an option to view mods in the game, do I need to download
another mod to show this?

**Comment by Svolpix** [comment]
actualy was having the same problem,u need first to extract the zip in another folder and then u need to leave the content on the titanfall 2 folder

**Comment by flynnito** [comment]
Ah, that fixed it. Thank you.
