### ISSUE TITLE
Access violation crash during gameplay

### ISSUE THREAD

**Issue by MaxineSN** [R2Northstar/Northstar#108]
Happened during gameplay on a gun game server that was running Colony. Can't seem to replicate the issue reliably but it's happened twice. Am running latest release 1.3.0.

[nslog04-01-2022 08-03-10.txt](https://github.com/R2Northstar/Northstar/files/7803649/nslog04-01-2022.08-03-10.txt)
[Dump file here](https://maxineis.gay/i/nsdump04-01-2022%2008-06-20.dmp)

**Comment by xracecar** [comment]
same problem, was on forward base kodai when it happened,
[nslog2022-01-21 14-19-01.txt](https://github.com/R2Northstar/Northstar/files/7916489/nslog2022-01-21.14-19-01.txt)
