### ISSUE TITLE
I get this error when I double click NorthstarLauncher

### ISSUE THREAD

**Issue by Juanlucapicardo** [R2Northstar/Northstar#11]
"The application was unable to start correctly (0xc0000005). Click OK to close the application". The solution I found online (related to other programs) was to reinstall, I've done so and it still shows me this error. The first time I launched the Launcher it asked me to put my Origin credentials, I logged in and checked the box for it to remember my password.

**Comment by Juanlucapicardo** [comment]
I also did what the user that created another guide on how to install it and the results are the same.

**Comment by p0358** [comment]
You're on Windows 7?

**Comment by Juanlucapicardo** [comment]
Yes

**Comment by GrapplePilotTF2** [comment]
Click "More Info"

**Comment by xia0** [comment]
> You're on Windows 7?

Do you know if Windows 7 is support planned?

**Comment by dudfunk** [comment]
How about Windows 8.1?

**Comment by SeriousGous** [comment]
Any working solution yet?

**Comment by AnonPilot35** [comment]
I have this problem, as well. Running Windows 11 and the EA Play app. Using Origin did not fix the issue. I have tried updating Windows and all of my drivers with Driver Booster; rebooting my PC; verifying the game files; restarting Origin/EA Play; running NorthstarLauncher.exe as Administrator; and re-downloading Northstar. None of these steps have worked.

**Comment by ChristmasLights** [comment]
Dearly desire a solution for this one.

**Comment by abarichello** [comment]
https://github.com/R2Northstar/Northstar/issues/65
