### ISSUE TITLE
Disabled mods in mods menu, what do i have to do

### ISSUE THREAD

**Issue by yeeter2003** [R2Northstar/Northstar#111]
I disabled all mods in the mods menue, now when i sttart titanfall2 northstar it just starts the normal game... whad do i have to do?

**Comment by x3Karma** [comment]
delete enabledmods.json in Titanfall2/R2Northstar

**Comment by GeckoEidechse** [comment]
As this seems to be a more common problem I added [a section to the wiki now](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#i-disabled-all-mods-and-now-i-cannot-re-enable-them-as-the-mods-menu-is-gone). ^^
Closing this under the assumption that the wiki entry should be enough to solve the problem.

@yeeter2003 if the steps described in the linked wiki page do not work for you or are not clear enough please re-open this issue.
