### ISSUE TITLE
Increase Epilogue dropship health

### ISSUE THREAD

**Issue by Casper1123** [R2Northstar/Northstar#112]
currently the Epilogue has a minor chance to crash the server when the dropship is destroyed (as far as I have seen), but the 10k hp is considerably too little, as now a single pilot can destroy it. This should be increased to vanilla hp.

**Comment by BobTheBob9** [comment]
should be fixed as of https://github.com/R2Northstar/NorthstarMods/commit/838dff86a1868e908c9c6b8d3f5f8255f82dbb7b
