### ISSUE TITLE
Remove Origin Authentication.

### ISSUE THREAD

**Issue by lay-by** [R2Northstar/Northstar#114]
Authenticating user's accounts with Origin's services is an unnecessary step that has caused bugs and poses a potential security risk for user's accounts in the event that the masterserver is compromised. Additionally, the removal of user authentication with Origin would help to significantly increase the size of TF2's playerbase as players would no longer need to posses a valid copy of the game to join community servers.

**Comment by hummusbird** [comment]
There are two issues with this. If no authentication is used, a route for spam attacks is opened up to attackers. The second point is invalid as the game is $5, cheaper on sites like G2A if you don't want to give EA any money.

**Comment by lay-by** [comment]
>The second point is invalid as the game is $5, cheaper on sites like G2A if you don't want to give EA any money.
I'm more concerned that EA will take Titanfall 2 off of stores soon similar to Titanfall 1, seeing how they've both been effectively abandoned by the company.

**Comment by DerpedCrusader** [comment]
I specifically would like to be able to load up Titanfall 2 on a flash drive, and give it to people at a lan party so we could all play locally.

Although I'm under the impression that there's ways around authentication in situations similar to this.

**Comment by hummusbird** [comment]
> 

there is - you can turn off authentication on your server and connect directly using the console

**Comment by Alystrasz** [comment]
> Additionally, the removal of user authentication with Origin would help to significantly increase the size of TF2's playerbase as players would no longer need to posses a valid copy of the game to join community servers.

Using Origin authentication somehow guarantees that Northstar is "only" an addition to Titanfall (a mod), and not a way to hack Titanfall, which is completely different from a legal point of view; have you ever heard of "cease-and-desist"?

**Comment by geniiii** [comment]
I'm pretty certain having the masterserver depend on Origin/Stryder authentication was intentional; it's simpler and lowers the risk of EA sending a C&D letter to the project.

**Comment by Juesto** [comment]
doing this would enable piracy which is not supported here, as well as bringing insecurity as pointed out by others

**Comment by abarichello** [comment]
Basically what https://github.com/R2Northstar/Northstar/issues/114#issuecomment-1005183940 said. Origin authentication will continue as default for now.
