### ISSUE TITLE
Ping issue-{Let us create public lobbie}?

### ISSUE THREAD

**Issue by tniromin** [R2Northstar/Northstar#117]
I use Singapore servers , after Respawn neglected the game last year the servers are mostly isolated. I then started using New York servers which had fair amount of players to play with (ping=200-300).
The Lobbies in northstar client (ping 300-600).
Appreciate the effort to create this client , this is simply a suggestion.
Thank you.

**Comment by hummusbird** [comment]
You can host your own public and private servers. There are instructions on the wiki

**Comment by abarichello** [comment]
https://r2northstar.gitbook.io/r2northstar-wiki/
