### ISSUE TITLE
[Feature Request] Team switch support

### ISSUE THREAD

**Issue by ArmoredPony** [R2Northstar/Northstar#119]
Unlike in original game lobby, there is no punishment for leaving the match early, so the teams get unbalanced quite often. Will be an option to willingly change your team added?

**Comment by x3Karma** [comment]
Willingly changing your team would be abused by griefers, just join a team and if it's losing, switch teams.

There are a couple of #northstar-mods that can help switch teams, such as Autobalance mod which may be what you're looking for.
