### ISSUE TITLE
Launcher Error - Solved

### ISSUE THREAD

**Issue by MarsalPh** [R2Northstar/Northstar#12]
I did everything as in the instructions for installation, after this i launch NorthstarLauncher as administrator, the console comes up but right after it i get this Launcher Error message:
 
 Failed to load the launcher DLL at  'C:\Users\(my pc username)\Desktop\custom server stuff\bin\x64_retail/tier0.dll':
 The specified module could not be found.
 
 Anybody with advice on this, because i am totally lost.
![Northstar error1](https://user-images.githubusercontent.com/96629280/147365148-3993a8b8-e7f6-4ac7-8000-ded447b79634.PNG)

**Comment by georgewoodall82** [comment]
You need to move all the files in custom server stuff to the root game folder

**Comment by MarsalPh** [comment]
> You need to move all the files in custom server stuff to the root game folder

I have already done this

**Comment by georgewoodall82** [comment]
Are you running the launcher through the game files too? Because in the image it looks like you have a copy of the launcher on your desktop that you are running

**Comment by MarsalPh** [comment]
> Are you running the launcher through the game files too? Because in the image it looks like you have a copy of the launcher on your desktop that you are running

No, i open the Northstart folder on the desktop, right-click on NorthstarLauncher and run as administrator. Of course after i have copied everything in the root game folder.

I put a copy of the launcher on my desktop as a stupid convinience move, but this gave me a different error so i deleted it now. But i did the rest exactly as in the instructions, now i verify game files and try again from start

**Comment by georgewoodall82** [comment]
you don't create a copy on the desktop, you create a shortcut of the launcher (from the game files) and put that shortcut on the folder

**Comment by MarsalPh** [comment]
> you don't create a copy on the desktop, you create a shortcut of the launcher (from the game files) and put that shortcut on the folder

Wow man thanks a lot! I have not read this anywhere else in the instructions but it works. After i copied the Northstar files on Titanfall 2 root folder, i right-clicked on the NorthstarLauncher.exe inside the titanfall 2 root folder and created a shortcut like you say. A new, second icon of the Launcher appeared, i grab this new shortcut and manually place it in the 'custom server stuff' folder on the desktop, and then run this shortcut as administratior, and it works! 
Thanks again a lot :)

**Comment by georgewoodall82** [comment]
Also, the shortcut does not have to be in the folder, it can just be an icon on the desktop

**Comment by MarsalPh** [comment]
> Also, the shortcut does not have to be in the folder, it can just be an icon on the desktop

Yes that was useful too, many thanks !!
