### ISSUE TITLE
Authenication failed.

### ISSUE THREAD

**Issue by Tare321GG** [R2Northstar/Northstar#122]

**Comment by Tare321GG** [comment]
Authenication failed. pls help me :(

**Comment by abarichello** [comment]
Check https://northstar.tf/discord announcements

**Comment by GeckoEidechse** [comment]
Ironically because the master server is down, the discord link also does not work.

But yeah, @Tare321GG the Northstar master server is down at the moment and as such authentication fails. Not a problem at your end and nothing you can do to fix it. Just wait a bit and try again later today.

**Comment by Tare321GG** [comment]
@GeckoEidechse thanks, I just installed it and the discord link dosen't work so I was worried.

**Comment by GeckoEidechse** [comment]
https://discord.gg/r2northstar should still work.
