### ISSUE TITLE
"Authentication failed"

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#124]
# Scroll to the bottom to see newest comment explaining the current reason.

***

Master server is currently down and as such using Northstar currently results in an error message "_Authenication failed_".

Check the `#announcements` channel in the Discord server for the current status.
You can join the Discord server via this link: https://discord.gg/r2northstar

**Comment by catornot** [comment]
when will the server be up?

**Comment by GeckoEidechse** [comment]
Master server should be back up again! :D

Keeping this issue pinned for a bit longer should there be issues again. As usual, the announcements channel on Discord is the place to get up to date information about the state of the master server.

**Comment by GeckoEidechse** [comment]
Master server is down again due to problems with hosting provider.

Check `#announcements` on the [Northstar Discord Server](https://discord.gg/northstar) for more info.

**Comment by alexrulez1** [comment]
hello,when will the server be up?

**Comment by xamionex** [comment]
No ETA. Check [#faq](https://discord.com/channels/920776187884732556/924643805746061342/930351503011627028) in the [discord](https://discord.gg/northstar) for a temp fix

**Comment by GeckoEidechse** [comment]
Should be back up again.

**Comment by alexrulez1** [comment]
ty

**Comment by GeckoEidechse** [comment]
Master server down while we investigate a security issue

**Comment by squallis** [comment]
when will the server be up?

**Comment by GeckoEidechse** [comment]
> when will the server be up?

No ETA but we will blast out messages with an update both on the [Discord](https://northstar.tf/discord) and this github issue, once the update is released and servers are back up.

**Comment by krishunt** [comment]
Thank you for your work on this.

**Comment by adamtheadmin** [comment]
Ya'll should go serverless

**Comment by GeckoEidechse** [comment]
> Hi! Master server is back up! Remember to download 1.6! It won't let you in without it. @GeckoEidechse you can close this
Thanks for the reminder ^^

Yes, master server is back up but it requires updating the game to `v1.6.0` or higher. You can grab the newest release from the [releases page here](https://github.com/R2Northstar/Northstar/releases).
If you're still getting `Authentication Failed` as an error message, make sure you're on the newest version of Northstar.

**Comment by krishunt** [comment]
I'm confused... launching NorthstarLauncher.exe brings the console up momentarily, and then it disappears and nothing further happens. Launching the original Titanfall 2 game loads the Northstar client. Why would it do this, and what if Respawn gets their act together and fixes the actual game; how would you then launch the original?

**Comment by BotchedRPR** [comment]
This does not happen to me. Sounds like a installation issue. Either join
the Discord or set up another GitHub issue, this is the issue for the
master server status.

wt., 29 mar 2022, 21:26 użytkownik Kris Hunt ***@***.***>
napisał:

**Comment by krishunt** [comment]
Well, it only started happening once I installed v1.6, so I thought it was relevant.
