### ISSUE TITLE
every time I try to launch NorthStar I get a error massage saying "failed reading origin path"

### ISSUE THREAD

**Issue by M00NLIGHT11** [R2Northstar/Northstar#128]
if i try to launch NorthStar I'm greeted with this message 
![image_2022-01-07_173147](https://user-images.githubusercontent.com/97319657/148620228-a80bc763-f0ad-4068-b391-6c747457057e.png)
If I press ok this happens
![image_2022-01-07_173207](https://user-images.githubusercontent.com/97319657/148620252-e55914c7-a45c-47a2-9bf5-b44783130198.png)
I dont normaly do this so it could be a really simple mistake but any help is appreciated

**Comment by abarichello** [comment]
Try this: https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#engine-error

**Comment by M00NLIGHT11** [comment]
this helped some but its now giving me a new message
![image](https://user-images.githubusercontent.com/97319657/148631523-d29d37fb-5d42-40f6-b168-1f13c1dbd5c2.png)

**Comment by abarichello** [comment]
#126

**Comment by M00NLIGHT11** [comment]
tysm this worked i can finaly move from console to pc titan fall and actually play
