### ISSUE TITLE
Game crashes - press esc when getting titan killed

### ISSUE THREAD

**Issue by MooMooMod** [R2Northstar/Northstar#13]
Recreated multiple times, just letting you know about it.

**Comment by HFDan** [comment]
+1 Also affected by this.
Opening the pause menu while getting executed in a titan leads to a crash.

**Comment by ASpoonPlaysGames** [comment]
potentially this issue is due to the first person animations?

**Comment by MiloAkerman** [comment]
This should be marked as info needed. Could you give a crash log? Minidump? Anything that might help solve this?

Also, might be solved by R2Northstar/NorthstarMods#173 but I can't tell without more info
