### ISSUE TITLE
Battery callout voice lines for male pilots playing despite using a female pilot

### ISSUE THREAD

**Issue by beebisalright** [R2Northstar/Northstar#130]
### Bug
When calling out that you're carrying a battery to a friendly titan, it will always play the male voice lines even if you have a female pilot selected.

### Steps to reproduce

  1. Select a female pilot in the loadout customization screen.
  2. Obtain a titan battery.
  3. Look at a friendly titan, and press the use key while at a distance.

### Specifications
  - Northstar version: 1.4.0
  - Platform: Steam

**Comment by IJARika** [comment]
This issue goes much deeper, pilots:
-all use the same voice, even males seem to all be the same
-don't say anything in the dropship
-don't comment on killls

**Comment by beebisalright** [comment]
> This issue goes much deeper, pilots: -all use the same voice, even males seem to all be the same -don't say anything in the dropship -don't comment on kills

ok seems like the pilot voice lines are just broken in general

**Comment by abarichello** [comment]
Fixed with https://github.com/R2Northstar/NorthstarMods/commit/24b9bfc941fcd84604d040443cc65f70602d920b
