### ISSUE TITLE
Cant launch NorthStar

### ISSUE THREAD

**Issue by Sek4r** [R2Northstar/Northstar#132]
![Screenshot 2022-01-09 111330](https://user-images.githubusercontent.com/97399471/148690637-0677acb8-bfb3-43e2-854f-84e2043945a5.png)

### Bug
Cant launch NorthStar

### Steps to reproduce
Followed the install instructions

### Specifications
  - Northstar version:1.4.0
  - Platform: Steam

**Comment by GeckoEidechse** [comment]
Try launching the vanilla game and see if it runs. If it does, try again with Northstar.

The error message seems to indicate that you're not logged into Origin.

**Comment by Homergali** [comment]
Will this work if I play the game using the Xbox pass on PC? I've tried running it with the north star client but keep getting a loading error and wont even open the game.

**Comment by Sek4r** [comment]
Ok ive figured it out

**Comment by Sek4r** [comment]
> Will this work if I play the game using the Xbox pass on PC? I've tried running it with the north star client but keep getting a loading error and wont even open the game.

open your own issue and you will get help

**Comment by Sek4r** [comment]
I have figured it out. I was just logged out of origin. After watching the Mokey video I redownloaded tf2 and then the northstar client but never ran the normal game.
