### ISSUE TITLE
Can't get into a server because "the lobby is full" even tho i checked again in server browser and it still wasn't full

### ISSUE THREAD

**Issue by H000man** [R2Northstar/Northstar#133]
### Bug
Replace this line with the bug you've encountered and what is the expected behaviour.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by abarichello** [comment]
https://github.com/R2Northstar/Northstar/issues/8

**Comment by H000man** [comment]
Everytime I try to join a server, it always puts me in the main menu with the message "!the lobby is already full" even tho when i checked back in the server browser, I could see that the server was still not full. This happens in any server even servers where no one is in.

**Comment by GeckoEidechse** [comment]
@H000man can you maybe add a screen recording?
Especially try to include joining empty and servers with a few players in them.

Also make sure you're on the newest version ([`v1.4.0`](https://github.com/R2Northstar/Northstar/releases/tag/v1.4.0))

It's hard to find the issue when we cannot reproduce the bug ourselves.
