### ISSUE TITLE
bug for north star

### ISSUE THREAD

**Issue by NickIsMyName2** [R2Northstar/Northstar#134]
north star 1.3 does not open right

### Bug
![Screenshot (7)](https://user-images.githubusercontent.com/97417103/148708894-e88ff0b4-1b22-4720-b48b-8641c0c8f5b3.png)
i cant open northstar without it saying there is an error and i cant figure out why
### Specifications
  - Northstar version:1.3
  - Platform: <-- Origin -->

**Comment by x3Karma** [comment]
Did you know 1.4 is released

**Comment by VITALISED** [comment]
Did you know 1.4 is released

**Comment by abarichello** [comment]
Try release 1.4.0

**Comment by NickIsMyName2** [comment]
> Try release 1.4.0

i fixed it by opening the game first
