### ISSUE TITLE
Map rotation runtime error

### ISSUE THREAD

**Issue by AnsonSkywalker** [R2Northstar/Northstar#135]
### Bug
The server is rotating to an incorrect game mode when the map is rotated automatically.

### Steps to reproduce
Chinese Titanfall2 player here.I used DeepL to help me translate this Issues so please excuse my grammatical errors.
1.I'm trying to set up a dedicated server and I'm having some map rotation issues.
2.In ns_startup_args_dedi.txt I set “+mp_gamemode” to tdm.(My server is Attrition Only so I choose Team Death Match)
3.In autoexec_ns_server.cfg I set "ns_private_match_only_host_can_change_settings" to 2 and "ns_should_return_to_lobby" to 0 in order to to avoid players modifying my server configuration in the lobby.
4.After I finished testing the server and it worked perfectly, I came back a few hours later to recheck the server and found that the game mode was incorrectly switched to "Attrition" during the auto-rotation and the scoreboard at the top of the HUD was not displaying the score properly (but the TAB still showed the number of kills for each player)
![Titanfall2 Screenshot 2022.01.09 - 22.17.39.76.png](https://s2.loli.net/2022/01/10/v7dj62RyqIbL5HZ.png)
(TAB translation: Score,kills,Titan Kills,Grunts Kills)
### Specifications
  - Northstar version:1.4.0_CN_HOTFIX
  - Platform: Steam(Dedicated Server on Windows Server 2019 Data Center Edition 64-bit Chinese Version)

**Comment by GeckoEidechse** [comment]
Assuming `1.4.0_CN_HOTFIX` is based on `v1.4.0`, that version is quite old and might already be fixed in newer versions. I'd suggest updating to the newest version of NorthtstarCN and if that still has the issue, opening a github issue on their repo. To my knowledge no one mentioned such an issue on base Northstar.
