### ISSUE TITLE
Steam Workshop support

### ISSUE THREAD

**Issue by ahydronous** [R2Northstar/Northstar#137]
This is more of a preliminary thing, but would it be possible to eventually get this added to the Steam Workshop?
Maybe Respawn would even be okay with giving this its blessing.

I think it would massively increase the reach of the project.

**Comment by abarichello** [comment]
The game hasn't been updated in years, there's no way they are adding mod support

**Comment by ahydronous** [comment]
They don't need to add it AFAIK? I don't know exactly how Steam Workshop works, but I often for games (even old ones) I see all sorts of mods on there that *definitely* would not be approved by 'corporate'.
