### ISSUE TITLE
authentication 

### ISSUE THREAD

**Issue by DonChino1** [R2Northstar/Northstar#138]
everything is downloaded properly and i restarted the computer, but when it comes to sending the authentication token to your servers, it continues to say it failed. hope there is a quick fix because i miss playing Titanfall 2

**Comment by Nova1xs** [comment]
same

**Comment by IAmJustTasty** [comment]
same here

**Comment by VITALISED** [comment]
https://discord.com/channels/920776187884732556/920780605132800080/930165554612961332

**Comment by abarichello** [comment]
https://github.com/R2Northstar/Northstar/issues/124

**Comment by DonChino1** [comment]
> https://discord.com/channels/920776187884732556/920780605132800080/930165554612961332

????
