### ISSUE TITLE
No Northstar Button to on multiplayer

### ISSUE THREAD

**Issue by Autocon487** [R2Northstar/Northstar#139]
I've downloaded and moved files with the guide, step by step. When I open the Northstar Client, I don't see the Northstar button under multiplayer, even the normal Multiplayer button is locked, saying "Contacting Respawn servers...."

**Comment by Autocon487** [comment]
![bug](https://user-images.githubusercontent.com/97491145/148871917-25a71b1a-981c-40ba-8190-83cf9776eca4.PNG)

Here is the what I'm seeing.

**Comment by abarichello** [comment]
Please read the issue template. If you need help installing or setting up a server you should check our wiki or help channels on discord.
