### ISSUE TITLE
Viewing map stats for Boomtown hard-locks the client

### ISSUE THREAD

**Issue by Jaco909** [R2Northstar/Northstar#14]
Attempting to open the map stats for Boomtown (second map in the stats list), will freeze all input in the client and require a forced shutdown through task manager.

**Comment by MiloAkerman** [comment]
Reproduced succesfully. Wtf.

**Comment by GeckoEidechse** [comment]
Still an issue in `v1.6.3`, damn o_O

**Comment by MiloAkerman** [comment]
Listen Gecko my esteemed fellow I haven't touched this game in a month because I fear even so much as opening this bug again will give me irreversible brain damage

**Comment by GeckoEidechse** [comment]
@MiloAkerman Emma actually found the issue and has a fix :D
Spoiler alert: The reason it happened in the first place is really stupid and is caused by Respawn's own code.

https://github.com/R2Northstar/NorthstarMods/pull/307

**Comment by emma-miler** [comment]
Fixed in 1.6.4

**Comment by GeckoEidechse** [comment]
https://github.com/R2Northstar/NorthstarMods/pull/307
