### ISSUE TITLE
'Access Violation' Crash

### ISSUE THREAD

**Issue by TrueCP6** [R2Northstar/Northstar#142]
### Bug
Game crash
[nslog2022-01-11 16-38-41.txt](https://github.com/R2Northstar/Northstar/files/7847566/nslog2022-01-11.16-38-41.txt)

### Steps to reproduce
Seemingly random. The same crash has occurred when joining a server and while in a game.

### Specifications
  - Northstar version: 1.4.0
  - Platform: Origin

**Comment by Xavierhorwood** [comment]
> 

have you tried to see if your game files are corrupted?

**Comment by MaxisTron** [comment]
I had this same problem, I tried to reinstall the game several times, as well as Northstar itself, but the game always crashes in the middle of the matches and every time I tried I couldn't play a full match

**Comment by TheWiggill** [comment]
I'm having this same issue.

**Comment by CyferShepard** [comment]
Im also having the same issue

**Comment by Shifulor** [comment]
This is happening to me too. I cannot run Northstar because of this. as soon as I launch it, this error appears and the game shuts down.

**Comment by Shifulor** [comment]
If this happens on Linux, u must use this proton Version: https://github.com/GloriousEggroll/proton-ge-custom/

**Comment by MaxisTron** [comment]
> If this happens on Linux, u must use this proton Version: https://github.com/GloriousEggroll/proton-ge-custom/

the thing is, i'm using Windows

**Comment by TheWiggill** [comment]
I discovered that the access violation crash occurs for me if I press the melee button during a killcam. Avoiding this case helped me get through games without crashing.

**Comment by MiloAkerman** [comment]
As mentioned in #180 none of your crashes are actually caused by access violations unless the memory trying to be read is not 0x000000.

**Comment by Dunrar** [comment]
I get this every game. Never managed to play for more then 3 minutes, most of the time I can't even get into a session.

**Comment by GeckoEidechse** [comment]
@Dunrar could open a new issue with information about your setup and current Northstar install?
