### ISSUE TITLE
Kunai as riff

### ISSUE THREAD

**Issue by xamionex** [R2Northstar/Northstar#143]
# Feature Request
### Maybe making it like a riff or custom setting? Would be awesome if it would speed up animation like the new OITC has

**Comment by hummusbird** [comment]
I can take a look at this. The Kunai is a completely different weapon with different stats to the regular melee, but it should be super easy to swap it out. Ill do the same for the pilot sword :D

**Comment by hummusbird** [comment]
R2Northstar/NorthstarMods#105 will close this

**Comment by xamionex** [comment]
dfgjsefnjksdfgriksfdlpsf accidental clos
