### ISSUE TITLE
Failed to load the tier0.dll at "C:\Program Files (x86)Origin Games\Titanfall2\bin\x64_retail\tier0.dll

### ISSUE THREAD

**Issue by brotherfromyourmother** [R2Northstar/Northstar#144]
### Bug
I have done everything as described in the installation guide: I downloaded the Northstar.release.1.4.0 folder, unpacked it, copied it into the TF2 folder and ran Northstar.exe as admin, resulting in the error message:  "Failed to load the tier0.dll at "C:\Program Files (x86)Origin Games\Titanfall2\bin\x64_retail\tier0.dll":
The stated module has not been found
### Steps to reproduce

  1. Downloaded the Northstar Launcher
  2. Unpacked the Northstar.release Folder
  3. Copied the unpacked files into the TF 2 folder
  4. Ran NorthstarLauncher as Admin

### Specifications
  - Northstar version: 1.4.0
  - Platform: Origin
![northstar](https://user-images.githubusercontent.com/97557403/149020194-6df1a263-8a24-452e-8701-aa70865e3dd3.png)

**Comment by xamionex** [comment]
Open Bin>Win64
If this folder is empty verify your game

**Comment by gerry-999** [comment]
I'm having the same issue, have tried troubleshooting everything and nothing seems to work

**Comment by Luna-foxx** [comment]
i had this happen to me when making a server
i installed directx and that fixed it 
i remember that issue having something to do with tier0.dll
but again that's server side never happened client side

**Comment by p0358** [comment]
If tier0.dll is in its place, then that means some dependency DLL is missing, which can in case of tier0 be one of:
* kernel32
* user32
* winmm
* OriginSDK

Honestly none of these should be missing from a healthy system, and OriginSDK.dll should also be in the folder by default.
Maybe Visual Studio redist 2022 is missing in such case?

**Comment by Luna-foxx** [comment]
this happened to me again c++ redist fixed it for me
i think it both needs directx and c++ redist 
tho it might just need c++ redist

**Comment by Joey451-OG** [comment]
> Open Bin>Win64 If this folder is empty verify your game

I have tried verified my game multiple times now and I'm not seeing Win64 or tier0.dll
