### ISSUE TITLE
"Windows cannot access the specified device, path, or file. You may lack permission" :I

### ISSUE THREAD

**Issue by Nemoquodeus** [R2Northstar/Northstar#145]
### Bug
Whenever I try to run the northstar launcher from the game's directory I get this message: "Windows cannot access the specified device, path, or file. You may lack permission" and then nothing happens. This persists despite admin mode as well.

### Steps to reproduce

  1. Download and unzip current Northstar client
  2. Copy it to Titanfall 2 directory
  3. Try to run it 

### Specifications
  - Northstar version: 1.4.0
  - Platform:  Steam, Windows 10

**Comment by redredgreengreen** [comment]
Bump, I have this too.

**Comment by ASpoonPlaysGames** [comment]
This might be an antivirus moment, had to help a friend fix it where the file would commit die every time he tried to boot the game, and then gave a similar error message, if possible, could you check your antivirus' quarantine and/or history and see if northstar is in there?
