### ISSUE TITLE
Getting this  error after the EA and Repawn logo

### ISSUE THREAD

**Issue by Skulkaaa** [R2Northstar/Northstar#15]
![error](https://user-images.githubusercontent.com/96631790/147368049-62698ac3-96a2-4dbd-b9ad-985b44c6e0bd.png)
Launching through origin

**Comment by AyrO667** [comment]
I had such a problem, it was due to the fact that I logged into another Origin profile that did not have TF2. I went to another profile with TF2 and the problem disappeared.

**Comment by OlegLime** [comment]
I have the same problem. Re-logging into my Origin account didn't help.

**Comment by GeckoEidechse** [comment]
Make sure you are on `v1.4.0` then follow this [troubleshooting section in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#failed-to-initialize-origin-origin-core-seems-to-be-running-but-the-lsx-authentication-challenge-fai).

**Comment by GeckoEidechse** [comment]
Also, duplicate of #126.

(Well technically the other one is the duplicate cause this one's older but oh well)

**Comment by GeckoEidechse** [comment]
If you still have problems after following [the section in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#failed-to-initialize-origin-origin-core-seems-to-be-running-but-the-lsx-authentication-challenge-fai) or have issues following please drop a message here or open a new issue.
