### ISSUE TITLE
No "run anyways" prompt

### ISSUE THREAD

**Issue by AlamTheVro** [R2Northstar/Northstar#153]
### Bug
I've done all the steps to download NorthStar onto my pc and transferred the files into the Titanfall 2 files and still came with the usual prompt saying "windows protected your pc" I hit "more info" expecting a "run anyways" prompt to show, but to no avail. only showing "don't run"  and nothing more. I've redownloaded TF2, reinstalled NorthStar, disabled anti-virus, disabled firewall, disabled windows defender, changed PC locations and language and still no "run anyways" prompts. 
![bruhhhhxd](https://user-images.githubusercontent.com/97852592/149676998-beef3fd6-645a-4bed-a26e-c0fa6b07475b.PNG)

### Steps to reproduce

  1. Unknown
  

### Specifications
  - NorthStar version: v1.4.0
  - Platform: origin (windows)

**Comment by abarichello** [comment]
This is not an issue on our end, try disabling all that microsoft bs and try again
