### ISSUE TITLE
Disconnect Authentication Failed

### ISSUE THREAD

**Issue by TrebtheTreb** [R2Northstar/Northstar#154]
![2c1bd8784eee7ae119ff0f8e4d072d27](https://user-images.githubusercontent.com/59307885/149797239-ddf721b9-21bb-4d8d-840b-28c64644d074.jpg)

### Bug
when you click launch northstar in the menu it pops up this error the master server is not offline. i am logged into origin and updated to newest release 

### Steps to reproduce

  1.launch northstar 
  2.
![378b1ab5ba10a29fd07119b1ea8d8f93](https://user-images.githubusercontent.com/59307885/149797822-13f77136-5ae2-4437-981f-c5464b66c3f0.png)

  3.

### Specifications
  - Northstar version:
  - Platform:  Origin

**Comment by abarichello** [comment]
Server issues, can you retry and see if it works?

**Comment by barnabwhy** [comment]
Looks like they're using my main menu mod.
To cut this short, something bugged the fuck out with the original release and authentication failures.
So i made a new release, just replacing the file linked in the message
(this being the new one https://cdn.discordapp.com/attachments/932432238216380466/932722797095034970/Barnab.ClientButSex_trimmed_down_less_issues_maybe.zip)

**Comment by barnabwhy** [comment]
Hopefully this solves the issue
