### ISSUE TITLE
Failed to initialize Origin : Origin seems to be running but the LSX Authentication challenge failed. no communication with the core is possible.

### ISSUE THREAD

**Issue by ARDARYUS** [R2Northstar/Northstar#159]
**Platform:Origin**
**Version: 1.4.0**

whenever i try to open northstar client it gives off this error 

Failed to initialize Origin : Origin seems to be running but the LSX Authentication challenge failed. no communication with the core is possible. [a1020002]
![error](https://user-images.githubusercontent.com/75616619/150550470-44dbe274-c2ba-48f7-9964-580646fe8e83.PNG)
-
i have read other bugs about this and they told me to write -northstar inside ns_startup_args and save and i did that but it still doesnt work i tried to launch it as administrator that didnt work either and im really confused can someone please help.

also i checked the debug text and i saw this 

[0119/182215:WARNING:resource_bundle_qt.cpp(114)] locale_file_path.empty() for locale
![error debug](https://user-images.githubusercontent.com/75616619/150550581-c0d83410-9c24-4133-afb6-adb141c5a71f.PNG)
-

**Comment by Baklojan** [comment]
same

**Comment by Luna-foxx** [comment]
starting the game from steam or origin with the -northstar tag should fix it
right click titanfall in steam > properties > launch options > type in -northstar > start game
my friend was getting that same error

**Comment by Luna-foxx** [comment]
use the northstar tag in steam 
with launch options

**Comment by GeckoEidechse** [comment]
> i have read other bugs about this and they told me to write -northstar inside ns_startup_args

As Luna-foxx said, `-northstar` needs to go in the game launch args in Origin , **NOT** in `ns_startup_args.txt`

See also #126 and [this section on the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#failed-to-initialize-origin-origin-core-seems-to-be-running-but-the-lsx-authentication-challenge-fai).
