### ISSUE TITLE
everyone crashes wile on rise map

### ISSUE THREAD

**Issue by Luna-foxx** [R2Northstar/Northstar#166]
### Bug
when playing on the map rise about half way thought the match everyone's games will crash only about 2-4 people will stay in the server
my friends report this has happened to them many times wile playing on the server
i have seen it about 3 times
i asked people after they rejoined and all of them said there client crashed

### Steps to reproduce

  1. play server on rise map
  2. have almost everyone on the server crash 

### Specifications
  - Northstar version: 1.4.0
  - Platform: steam

**Comment by laundmo** [comment]
what gamemode were you playing when this happened? was there any error message?

**Comment by Luna-foxx** [comment]
i have not been able to check console when this happens as its kind of random during the match
but if it happens again ill try to see if there was an error message ill tell my friend this happens a lot that if they get an error to tell me. (i have never crashed from the map before i have only seen other people crash from it)
the gamemode was Skirmish

**Comment by Luna-foxx** [comment]
update: this does not only happen on rise (i no longer think its the map doing it)

**Comment by xamionex** [comment]
Does it happen on the same server?

**Comment by Luna-foxx** [comment]
i had this happen on 3 of my servers all run on separate machines all set up manually
