### ISSUE TITLE
Failed to load the vpk for "vpk/client_mp_common.bsp"

### ISSUE THREAD

**Issue by HuskyArts** [R2Northstar/Northstar#167]
### Bug
When launching the Northstar Client instead of the game properly starting i get an Engine Error Saying the Following:
Failed to load the vpk for "vpk/client_mp_common.bsp"
(I get to the EA logo but past that i get that error)

Heres a Link to the Log that Northstar Generated:
https://pastebin.com/eHG58zzr

### Steps to reproduce
  1. Open the Location at which Titanfall 2 is stored (D:\Program Files (x86)\Origin Games\Titanfall2)
  2. Drag and Drop the Northstar Files as instructed 
  3. Run NorthstarLauncher.exe and after the EA Logo i encounter the Engine Error

### Specifications
  - Northstar version: v1.4.0
  - Platform: Origin

### PC Specs
  - Windows 10 Pro 10.0.19042
  - Intel Core i9 9900K
  - Nvidia GeForce RTX 2080ti
  - 32GB of DDR4 Ram

![Screenshot_10](https://user-images.githubusercontent.com/28672338/150696713-35b5d642-112a-4bde-a260-f23e76e841f4.png)

**Comment by HuskyArts** [comment]
I Should also mention I have a 32:9 Monitor, perhaps that plays some part in the game not launching properly.

**Comment by GeckoEidechse** [comment]
What happens if you launch the base game without Northstar? Do you get the same error or does it work just fine?

**Comment by HuskyArts** [comment]
> What happens if you launch the base game without Northstar? Do you get the same error or does it work just fine?

Nope works just fine Both Launching the .exe Directly and via the Origin Launcher. In the Meanwhile ive also [followed these Instructions](https://www.reddit.com/r/titanfall/comments/59trzd/failed_to_load_the_vpk_for_vpkclient_mp_commonbsp/) and Repaired the game files but to no evail. (I Readded the Northstar Files just in case the Repair broke something)

**Comment by abarichello** [comment]
Check your Titanfall installation for missing files/wrong permissions/enough free space, this doesn't like a Northstar problem
