### ISSUE TITLE
Failed to load the tier0.dill

### ISSUE THREAD

**Issue by HauntedHydration** [R2Northstar/Northstar#168]
Bug 126

![image](https://user-images.githubusercontent.com/98285996/150698174-a4fbec01-e18e-45fe-9a6e-448a3b23a7d3.png)

126 Steps to reproduce

  1. Downloaded 1.4 and moved the extracted files to the titanfall steam folder
  2. double click northstar launcher
  

126 Specifications
  - Northstar version: 1.4
  - Platform:  Downloaded through steam but booting through both.

**Comment by xamionex** [comment]
Read #faq in the discord, Not a bug you just installed incorrectly

**Comment by HauntedHydration** [comment]
Will to, thanks for the help and quick response
