### ISSUE TITLE
UI is cutoff on 4:3 monitors

### ISSUE THREAD

**Issue by bazookaben** [R2Northstar/Northstar#17]
So with `mat_letterbox_aspect_goal 1.33` and `mat_letterbox_aspect_threshold 1.33` in autoexec.cfg, you can play the game in 4:3 (I still rock a 4:3 CRT, playing at 1920x1440 @ 90hz)

The games standard UI normally gets cutoff on the left and right edges. But maybe it's possible to get Northstar's UI to conform to a letterboxed 16:10 region on monitors taller than 16:10?

 I'll post a screenshot below, it looks like the UI is left justified instead of centered, but I'm not sure:
![4x3 UI](https://user-images.githubusercontent.com/36523399/147369035-1684b203-b1d5-46d2-bd6b-66b4b9f6d9b8.jpg)

**Comment by GeckoEidechse** [comment]
Putting
```
mat_letterbox_aspect_goal 1.33
mat_letterbox_aspect_threshold 1.33
```
as described, I cannot get 4:3 to work. Am I missing anything?

**Comment by GeckoEidechse** [comment]
Also it's been quite a while since this issue is opened, so this might no longer apply. @bazookaben would be great if you could update us with how much this is still an issue. ^^

**Comment by bazookaben** [comment]
Hey sorry I forgot to respond to this. 

First off, I should mention that this really isn't a a Northfall issue, Titanfall 2 has always behaved this way with these command line arguments.

So here are the actual commands:

`+mat_letterbox_aspect_goal 1.33
+mat_letterbox_aspect_threshold 1.33`

And these commands won't activate until you hit alt+enter

And I found that the menu is actually displayed in whole _if_ you hit alt+enter on the title page. If you activate later, the menu gets cropped. 

And I should mention that HUD is always cropped. This is aslo a Titanfall issue, not a Northstar issue
![Titanfall 2 4x3 HUD](https://user-images.githubusercontent.com/36523399/171306642-bcccb91d-8a68-4fcd-83d5-df10f366f773.jpg)

Not game breaking, but I can't really use the minimap.

So all this to say: do you guys think it's possible to create a 3rd command line argument that preserves the HUD when using taller-than-16:10 aspect ratios? Either by locking the elements to the edges of the screen, or just preserving the 16:10 HUD in the middle section of the screen?

**Comment by GeckoEidechse** [comment]
> So all this to say: do you guys think it's possible to create a 3rd command line argument that preserves the HUD when using taller-than-16:10 aspect ratios?

I fear that might be too much work without enough payout, especially as there is the `Alt+Enter` workaround in menu screens as you mentioned :/

Regarding the in-game HUD, there are mods like [HUDRevamp](https://northstar.thunderstore.io/package/EladNLG/HUDRevamp/) that move around HUD elements. One could probably make a mod based on it to move the position of minimap, titanmeter, killfeed, ... further inward. Maybe try contacting the author of that mod on their GitHub repo to see if they'd be interested in adding parameters that allow moving the remaining elements (some, like abilities and ordnances can already be moved). ^^

**Comment by bazookaben** [comment]
Thanks for pointing me in the right direction.
