### ISSUE TITLE
Cannot access Northstar at all.

### ISSUE THREAD

**Issue by IOnlyPostIssues** [R2Northstar/Northstar#174]
### Bug
I have followed all installation instructions exactly as specified, but upon starting TF|2 through the Northstar launcher, it does not show the "+Northstar" title and it is stuck eternally connecting to servers.

### Steps to reproduce
  1.  I followed the installation steps.
  2.  Launched from the Northstar Launcher.
  3.  Profit?

### Specifications
  - Northstar version: 1.4.0
  - Platform: Origin
  - Specs: i5 10400F Gen 10 (yes, I already did the OpenSSL variable fix, I can run the vanilla game just fine), GTX 1070TI 8GB, 32 GB DDR4 RAM @ 3200Mhz

**Comment by GeckoEidechse** [comment]
The fact that `+Northstar` is missing from the menu screen implies that something is wrong with the mods part of your install.

I'd suggest the following steps, testing Northstar after each time to see if it works

- Reinstall Northstar by [following the install steps described in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup)
- Check that in the directory `Titanfall2\R2Northstar` the folder `mods` exists and contains `Northstar.Client`, `Northstar.Custom` and `Northstar.CustomServers`.
- If in `Titanfall2\R2Northstar`, the file `enabledmods.json` exists, delete it, then launch Northstar.  
   The file is used to check which mods are enabled and disabled. If you disable all the mods the only way to enable them again is by deleting this file and letting Northstar recreate it.

If after all of this you still have problems, please re-open this issue. Also attach screenshots to further help us narrow down the problem.

**Comment by IOnlyPostIssues** [comment]
It was that I had incorrectly installed it somehow, as Gecko said.
I used Viper as suggested by someone in the Northstar Discord server and Northstar worked flawlessly.
