### ISSUE TITLE
The "Access violation" error

### ISSUE THREAD

**Issue by MAETEXX** [R2Northstar/Northstar#179]
Hello! I downloaded this mod not so long time ago and keep getting one same issue at the end of every session. I attach the logs folder that contain it lower. 
[logs.zip](https://github.com/R2Northstar/Northstar/files/7979498/logs.zip)

**Comment by MiloAkerman** [comment]
Hello, could you please provide a picture of the text you get on crash? The logs folder isn't providing much information.

**Comment by rartigues** [comment]
I started having the same problem. Only change in my system is that I updated Windows 11 + Nvidia drivers

https://i.imgur.com/AHiUrWn.png
