### ISSUE TITLE
[Titan Brawl] Switching pilot class will switch you into a pilot.

### ISSUE THREAD

**Issue by Erlite** [R2Northstar/Northstar#18]
- Spawn in.
- Immediately switch pilot class once your titan has landed.
- Your titan disappears, and you're a pilot now.

Also has the unfortunate side effect of letting you call another titan once you fill your meter, allowing for titanfall kills.
Attempting to get inside your titan gives one of the following outcome:

- You immediately blow up and die.
- Sometimes, the server just outright crashes.

**Comment by Erlite** [comment]
What I saw after getting into my newly called titan, the server crashed a second later.
![image](https://user-images.githubusercontent.com/25248023/147369974-370755b7-cd4b-491d-bb52-c2f86732fcb4.png)

**Comment by BobTheBob9** [comment]
should be fixed on newest NorthstarMods commit, i'll push a release soon so let me know if it's fixed then
