### ISSUE TITLE
Global banned from server(cant connect to NS lobby)

### ISSUE THREAD

**Issue by WordBearersXVII** [R2Northstar/Northstar#182]
### Bug
My GF get banned by server owner bc she just good player. But now she cant to connect to ns lobby with this error. She reinstalled the game and northstar without my knowledge, and now her banlist.txt in r2northstar clear, but error still alive.
### Steps to reproduce

  1.Get banned by any server's owner
  2.Try to connect NS lobby
 

### Specifications
  - Northstar version:1.4
  - Platform:  Origin

https://sun9-52.userapi.com/impg/Drp8j4o-P0WF_IjmNcVoavBPh3NXo76XA5BiYg/YfyqYMSM7gQ.jpg?size=1920x1080&quality=95&sign=70c3bf68561461b34334f572179c814b&type=album

**Comment by GeckoEidechse** [comment]
Global bans aren't a thing yet and `banlist.txt` only lists the people you banned from your own server (or you want to ban by adding them to the file) when you host one.

You can only get banned from individual servers at the moment by the server owner taking manual action. If you wanna know why you got banned, ask the owner. Nothing we can do.
