### ISSUE TITLE
everytime i launch northstar i get an error message even though ive checked if files are up to date and have reset my pc its sorta like ive been ddosed

### ISSUE THREAD

**Issue by Enter-a-username6** [R2Northstar/Northstar#189]
### Bug
Replace this line with the bug you've encountered and what is the expected behaviour.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by abarichello** [comment]
Read pinned issue https://github.com/R2Northstar/Northstar/issues/187#issuecomment-1034579966
