### ISSUE TITLE
Investigate possibility of loading main menu videos as "mods"

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#199]
The main menu background video in Titanfall2 is a file called `menu_act01.bik` located in `Titanfall2\r2\media`. If a player wants to change their main menu video they simply have to create a file in the appropriate format, name it  `menu_act01.bik` and place it in `Titanfall2\r2\media`, overwriting the old one in the process.

While this process is not too difficult, it might be useful to investigate a hook that allows redirecting loading the menu video from a different location.
(Exact implementation details should be whatever is easiest/best to implement)

The idea is that a player can download the main menu video as "mod" from [Thunderstore](https://northstar.thunderstore.io/) and switch between multiple main menu videos by disabling/enabling mods.

This could both be useful in improving user experience and allows us to keep "one standard" format for different kinds of mods. Additionally this means base game won't be touched by such a mod.

**Comment by ConnorDoesDev** [comment]
I like this.

**Comment by GeckoEidechse** [comment]
Another reason to do this. We could ship our own background for special themed releases. For example for a new major release that has a corresponding trailer we re-use (parts of) the trailer to create a custom menu background.
(We could technically already do this by including the menu video in the release zip in such a folder structure that it overwrites the existing one but the issue is reversibility and generally trying to avoid messing with basegame files)


Similarly we could change the background during specific times of the year. Let's say something spooky but only if the clock on the player's device is set to the time around Halloween.
(This could only be done if we figure out a way to hook the call to the video file as replacing the menu video file is a more permanent action :P)

**Comment by ConnorDoesDev** [comment]
Yes! I like this idea. I think it should be possible to overwrite that file and back it up somehow.

**Comment by GeckoEidechse** [comment]
This has been working for quite a while now. Not sure what update enabled it but it works.

See for example: https://northstar.thunderstore.io/package/GeckoEidechse/Titanfall1IntroVideo/
