### ISSUE TITLE
better install instructions

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [R2Northstar/Northstar#2]
[the install instructions](https://github.com/R2Northstar/Northstar/wiki/Basic-Setup) are ambiguous if they want you to extract the contents of `custom server stuff` to the Titanfall 2 install folder, or id you should put the contents of the folder in the Titanfall 2 folder.

It's the latter, but of course I picked the wrong one the first time around. The instructions should be updated to clarify this,

**Comment by ImTastyLotus** [comment]
Im still confused, I extracted all the zip files to my Titanfall 2 folder and updated the game through origin. when I launched nothing changed, am I missing something?

**Comment by SIGSTACKFAULT** [comment]
> Im still confused, I extracted all the zip files to my Titanfall 2 folder and updated the game through origin. when I launched nothing changed, am I missing something?

you're better off asking at https://northstar.tf/discord

**Comment by SleepDaemon** [comment]
[https://rentry.org/northstar-dl](url)

i've made this guide on how to install it, if there anything you want to change/remove/add just let me know.

**Comment by SleepDaemon** [comment]
> [How To Install Northstar Guide](https://rentry.org/northstar-guide)
> 
> i've made this guide on how to install it, if there anything you want to change/remove/add just let me know.

updated the link

**Comment by zbot473** [comment]
If we want to contribute to the wiki, there could be a docs folder in the [Northstar](https://github.com/R2Northstar/Northstar/) repo which has an action to push markdown pages to the wiki.

**Comment by FutzMonitor** [comment]
> [How To Install Northstar Guide](https://rentry.org/northstar-guide)
> 
> i've made this guide on how to install it, if there anything you want to change/remove/add just let me know.

I would also add to the noted section that you cannot host _Frontier Defense_ on the private servers. I had a couple friends download the source files and were a bit disappointed to see that they couldn't play that game mode.

**Comment by SleepDaemon** [comment]
the guide isnt about how to host, its how to install the client

**Comment by GeckoEidechse** [comment]
Since this issue was opened we now also have a [more proper wiki](https://r2northstar.gitbook.io/).
This also includes reworked install instructions which can be found here: https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/basic-setup

@SIGSTACKFAULT (and everyone else in this thread) what's your impression? Are there things we should still change before closing this issue?

**Comment by abarichello** [comment]
Closing this for now, feel free to contribute to the wiki if you think anything's missing.
