### ISSUE TITLE
Suggestions to improve the REAMDE

### ISSUE THREAD

**Issue by PhantomDerp** [R2Northstar/Northstar#20]
Add a link to the releases and install instructions to the README for the people that have never used github before

Mention that you should rename Northstar.exe (whatever the name is) to Titanfall2.exe so you can start the game from steam.
Renaming Northstar.exe is also the easiest way for Linux users to use this with proton

**Comment by p0358** [comment]
Actually the startup process might get reworked to not need that, I developed that along with a way to fix the corruption error for good, but still needs to be polished out before PR

**Comment by FutzMonitor** [comment]
My pull request makes changes to the README.md with the addition of the INSTALL.md. It will be updated as installation instructions may changer over time.

**Comment by abarichello** [comment]
Closing since the wiki/readmes got a new look. Thanks everyone
