### ISSUE TITLE
Multiplayer Opening Crash

### ISSUE THREAD

**Issue by SomerandomguyonGitHub** [R2Northstar/Northstar#204]
I'm trying to play Northstar multiplayer, but every time I click "Launch Northstar," it loads up for a couple seconds and then crashes. It opens a little window that says, "Northstar has crashed! A crash log and dump can be found at R2Northstar/logs. I also can't find the crash logs, so idk what's happening.

**Comment by GeckoEidechse** [comment]
Make sure you're running `v1.4.2` or higher and **don't** use a mod that modifies the main menu UI. The crash is likely a result of an attack against Respawn servers where players in the Advocate Network get crashed out of the game. Newer versions of Northstar mitigates this attack.
