### ISSUE TITLE
Spawns Locked In One Location

### ISSUE THREAD

**Issue by NorFox36** [R2Northstar/Northstar#205]
### Bug
Spawn areas are not switching positions and only sticking to one location. When the spawns are like this the game grinds to a halt and turns each match into a spawn camping bore. I'm unsure if this is on all game modes, but in skirmish its always the case. I have no clue what the latest update did to have this happen because it was working as intended before 1.5.1. (unsure if it has something to do with the CTF spawn algorithm change). I hope it can get looked into because its super unfun to play it now when 1. it turns into who can spawn camp better, and 2. The whole map gets closed off with only activity in one area. When both teams only spawns in the same spot every time there's no point in going elsewhere. I hope this gets fixed because it doesn't feel like Titanfall anymore when you just spawn in the same two areas every time.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by GeckoEidechse** [comment]
I'm closing this due to missing Northstar version and lack of updates. There have been many changes since so it's not clear whether this is still an issue.

**Comment by NorFox36** [comment]
It is still an issue, i popped in for a match and its still the exact same. If its needed i'll write a longer explanation on the issue with pictures if my point didnt come across. My theory is still with the CTF spawn algorithm change that happened in v 1.5.1 _''New spawnzone algorithm for CTF''_ is probably where the problem is. The problem with the spawns wasnt happening before that update. Let me know if you need me to explain further.

**Comment by GeckoEidechse** [comment]
How did you test it? Just start a private match and suicide?

**Comment by NorFox36** [comment]
No, i joined a public server (Skirmish) that was full enough and played for abit. Still same exact areas that the spawns are locked to since last time i played which has been a like two months. When i tested this before i played several other game modes, maps, whatever and still for all of them they had the same problem.

**Comment by GeckoEidechse** [comment]
Aight, tagging @BobTheBob9 :3

**Comment by Zanieon** [comment]
Closing, issue fixed with https://github.com/R2Northstar/NorthstarMods/pull/829
