### ISSUE TITLE
Failed to initialize Origin, LSX Authentication Challenge failed

### ISSUE THREAD

**Issue by PSTL002** [R2Northstar/Northstar#209]
help this is the latest version
![brok](https://user-images.githubusercontent.com/100746820/156301246-2679b144-9aa3-48a9-908f-2695da0ab552.PNG)

**Comment by cwainwright** [comment]
Getting the same issue here, reaches loading screen right before main menu and then goes to whitescreen, this error appears in background.

**Comment by GeckoEidechse** [comment]
Have you tried [the fix described in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#launch-opts)?

Also, make sure Origin is already running before starting Northstar.

**Comment by rafaelb07** [comment]
same problem

**Comment by cwainwright** [comment]
Fixed the issue by adding -northstar to the Launch Options in Steam

**Comment by rafaelb07** [comment]
i used origin already tried , dosnt work
