### ISSUE TITLE
Engine Error - Received invalid playlist override value length

### ISSUE THREAD

**Issue by ABAxStorm** [R2Northstar/Northstar#23]
Upon trying to join a server, game can crash with "Engine Error - Received invalid playlist override value length: 150."
![unknown](https://user-images.githubusercontent.com/93966120/147372680-2058b208-a906-4cb2-a1b3-1502bae83b63.png)

I saw at least one other user in the discord with this issue.

Love you <3

**Comment by BobTheBob9** [comment]
is this still an issue you have? i've implemented a patch to prevent it and i've not really heard much about it being an issue since then

**Comment by SIGSTACKFAULT** [comment]
@ABAxStorm is your client up-to-date?
