### ISSUE TITLE
1.6 crashes when opening campaign

### ISSUE THREAD

**Issue by BotchedRPR** [R2Northstar/Northstar#231]
### Bug
Campaign crashes on Northstar 1.6. Northstar produces a crash dump. No campaign levels work, not even gauntlet

### Steps to reproduce

  1. Update to Northstar 1.6
  2. Open game (I'm doing it from Steam)
  3. Try to play any campaign level

### Specifications
  - Northstar version: 1.6
  - Platform: Steam
[northstar.zip](https://github.com/R2Northstar/Northstar/files/8372618/northstar.zip)

**Comment by H0L0theBard** [comment]
The campaign access violates shortly after
`CLIENT SCRIPT COMPILE ERROR Undefined variable "AddCallback_GameStateEnter"` in state_client.nut.
This seems to be a DiscordRPC issue.

**Comment by possiblyRZ** [comment]
Saw the other post about game crashing when discord is closed, tried loading a campaign level after deleting ``DiscordRPC.dll``. Game still crashes.

**Comment by H0L0theBard** [comment]
![image](https://user-images.githubusercontent.com/97146561/160733881-0ad83c0d-bc74-46a9-a3ca-58aa29b13523.png)

A simple fix can be done in both state_ui.nut and state_client.nut which are in NorthstarMods
It will prevent the crash but doesn't display all the information as it hasn't been set up for the campaign.

**Comment by GeckoEidechse** [comment]
Fix is in https://github.com/R2Northstar/NorthstarMods/pull/285 and was released with `v1.6.2`. So that version and newer ones should not have this issue.
