### ISSUE TITLE
Northstar refuses to launch if you do not have Discord installed.

### ISSUE THREAD

**Issue by J0w03L** [R2Northstar/Northstar#233]
### Bug
NorthstarLauncher.exe fails to launch when your computer does not have Discord installed.
Attempting to run Northstar on a computer that does not have Discord installed will result in an error which can be seen very briefly before the application closes itself (unless you run from a command prompt):
`Failed to instantiate discord core! (err 4)`

### Steps to reproduce

  1. Install Northstar 1.6.0 on a computer that does _not_ have Discord installed.
  2. Try to launch the game through Origin or Steam

### Specifications
  - Northstar version: 1.6.0
  - Platform: Origin & Steam 

![image](https://user-images.githubusercontent.com/75956156/160662457-65d66ba0-9a71-46cb-9a8c-017407318bad.png)

**Comment by pg9182** [comment]
duplicates R2Northstar/NorthstarLauncher#130

**Comment by pg9182** [comment]
For now, this issue can be worked around by deleting `DiscordRPC.dll` from the plugins folder.

**Comment by GeckoEidechse** [comment]
Actually it's enough to have Discord fully closed.

To reproduce:
1. Close Discord fully (i.e. don't just hit the X and minimise to task bar)
2. Launch `NorthstarLauncher.exe`
3. Launcher will open for a split-second and then close out again.

**Comment by B0btheBob9** [comment]
While less-invasive measures are now the preference going forward, it remains paramount to keep cheaters barred from our ecosystem. We've been able to observe an interesting pattern among the population of cheaters which have popped up within Northstar, and one common thread between them all has been the ability to actually launch the game. The fewer users who are able to launch the game, the fewer potential cheaters that results in. We've made the claim before of taking competitive integrity very seriously, and this hotfix is in no way a departure

**Comment by Coopyy** [comment]
very cool approach bob 👍

**Comment by emma-miler** [comment]
real b0bthebob9 :trollface:

**Comment by Coopyy** [comment]
where bob go

**Comment by ASpoonPlaysGames** [comment]
bob is kil

**Comment by Coopyy** [comment]
pain

**Comment by GeckoEidechse** [comment]
Seems fixed with https://github.com/R2Northstar/NorthstarDiscordRPC/commit/55dc2cc6080a0f8348b015d602cd4c02b5b0e06f

Will be in next update ^^

**Comment by GeckoEidechse** [comment]
Should be fixed with  [`v1.6.1`](https://github.com/R2Northstar/Northstar/releases/tag/v1.6.1).
