### ISSUE TITLE
1.6 crashes with proton version 7.3-GE-1

### ISSUE THREAD

**Issue by jpechg** [R2Northstar/Northstar#234]
### Bug
After updating the Northstar client to 1.6, the previous setup I had, which worked and used this proton version does not work, giving a Data Execution Prevention (DEP) at: 0x00000000 error.
### Steps to reproduce
  1.Setup northstar as determined in the wiki
  2.update to 1.6
  3.launch the game

### Specifications
  - Northstar version: 1.6
  - Platform: Steam, In artix linux with xfce and pipewire, zen kernel

**Comment by pg9182** [comment]
Can you post your logs up to the point where it crashes?

**Comment by jpechg** [comment]
nvm i just recompiled the kernel and for some reason it works now
