### ISSUE TITLE
Executable nott opening 

### ISSUE THREAD

**Issue by maurozin** [R2Northstar/Northstar#235]
### Bug
I have installed in the game path, but when i try to open the northstar executable only oppens a prompt window and its closes quickly, nothing happens after this

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version: the last 
  - Platform: Ea desktop

**Comment by Saitam305** [comment]
I have a similar issue, currently removing any mods left from 1.5.1 (Including HaloAnnouncer2.0, Odds.Scoreboard, Fifty.NorthstarSpinner, Fifty.SimplifiedMenu) and any R2 files. I run Titanfall 2 from Steam and I have the same issue. I will report back if scrubbing my mods folder did anything.

**Comment by GeckoEidechse** [comment]
From the announcements channel on the [Northstar Discord](https://northstar.tf/discord):

> There is a known issue with 1.6.0 where if discord is not open when you start the game, it will immediately close
>  This issue will be resolved for 1.6.1 (hopefully)
> For now, if you have this issue just delete R2Northstar/plugins

**Comment by GeckoEidechse** [comment]
Closing due to lack of response. Likely a duplicate of #233 anyway.
