### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by Rbarzevedo** [R2Northstar/Northstar#24]
Every time I click "Launch Northstar", it tells me "Disconnected: Authentication failed." I clicked "yes" on that first pop-up regarding the authentication but nothing happens.

**Comment by Puzkaujuzzi** [comment]
I am having a similiar issue, although I am able to get to the server browser. However if I click on a server the tf2-unpacked.exe console thing tells me "Attempting authentication with server of id..." and nothing happens.

And when selecting private match the console tells me a server spew_message that the level has been changed to mp_lobby but on the Titanfall 2 client nothing happens, it just stays on the multiplayer menu

**Comment by abarichello** [comment]
This error happens when the game can't connect to the master server, should be working now
