### ISSUE TITLE
Open the Wiki as a tab in your browser instead of the origin browser

### ISSUE THREAD

**Issue by biast12** [R2Northstar/Northstar#245]
Think it could be so much more useful if the [wiki](https://r2northstar.gitbook.io/r2northstar-wiki/) is opening in your actual browser when you click the tab (like discord does) instead of opening it in our origin browser

![image](https://user-images.githubusercontent.com/53872542/161881233-0497d8ac-5458-4e40-b377-60f152fe3dde.png)

**Comment by abarichello** [comment]
Not really a Northstar issue, there seems to be a problem with how your OS/Origin configuration handles links

**Comment by biast12** [comment]
No it's not, the discord link is opening in the normal browser as a new tab, it's only the wiki that opens in the origin browser

Also this is a suggestion to get added....

**Comment by abarichello** [comment]
Weird, on Linux all links including the wiki one open through the default browser

**Comment by biast12** [comment]
> Actually @biast12 is right, we added logic to always open Discord links in browser instead of Origin overlay one and we could probably do the same for wiki [by adding some logic here](https://github.com/R2Northstar/NorthstarMods/blob/main/Northstar.Client/mod/scripts/vscripts/ui/panel_mainmenu.nut#L929).
> 
> It's more of a design decision than a technical one whether we want to change that ^^

Yep! i had a look myself (i was planning on making a pull request), tho i couldn't find where the wiki was being opened so i thought making a suggestion would be better instead (to leave it to someone who knows where it is)
