### ISSUE TITLE
Crashing when respawn on Attrition

### ISSUE THREAD

**Issue by E3VL** [R2Northstar/Northstar#250]
### Bug
During respawn, you disconnect to main menu. Every time. It only happens to some clients.

### Steps to reproduce

  1. Host a Attrition server
  2. Kill enemy
  3. Grunts also work

### Specifications
  - Northstar version:1.6.1
  - Platform:  Origin

[nslog2022-04-10_03-51-42.txt](https://github.com/R2Northstar/Northstar/files/8458682/nslog2022-04-10_03-51-42.txt)

**Comment by GeckoEidechse** [comment]
Do you recall if this happened on any specific Attrition server or all of them?
