### ISSUE TITLE
Allow hot-reloading `banlist.txt`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#251]
Currently for an edit in `banlist.txt` to get applied to a dedicated server, the server needs to be restated.

Instead, the server should just reload the file when changes are made so that server owners can edit their banlist without having to restart their server for the change to take effect.

Regarding the exact implementation, very frequent updates like checking for file system changes etc. is probably overkill. A suggested solution was to reload the list on every connection event (i.e. player joining the game). That's an event that gets triggered enough for the change to take effect fast enough, while also being rare enough to not slow down the server too much (like for example reloading on every tick would).
Preferably we should read out the list and apply it before allowing a player to proceed and join the server, to prevent edge case scenarios where a player gets banned on a server that sees no players joining but after applying the change in banlist, the first player to join is the banned one. If the file only gets reloaded after the join event, the player can still join the server (at least until leaving again).

**Comment by emma-miler** [comment]
Probably easiest to watch for file changes using something like [FindFirstChangeNotificationA ](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstchangenotificationa) running in a thread.

For thread safety, my first idea would be to replace `std::vector<uint64_t> m_vBannedUids;` with a `std::vector<uint64_t> *m_vBannedUids;` and swap around the pointer value whenever we have instantiated the new vector from the wait thread. Ideally you'd even use a smart pointer for this, but i'm not knowledgeable enough in c++ to make any recommendations on that.

**Comment by emma-miler** [comment]
Just had a talk with pg about this, and the solution proposed above is unfortunately not very portable for docker and wine. Probably the best option would be to load it from disk after every connect in a thread, and adding a concommand to reload it. Shouldn't hit the disk too often due to fs cache, and moves the reloading out of the hot path for connects.

**Comment by dilirity** [comment]
Heads up - I tried tackling this here https://github.com/R2Northstar/NorthstarLauncher/pull/164.

**Comment by GeckoEidechse** [comment]
Closed as completed with https://github.com/R2Northstar/NorthstarLauncher/pull/164
