### ISSUE TITLE
Game menu has nothing in it just the background

### ISSUE THREAD

**Issue by ItsTheRealAB** [R2Northstar/Northstar#260]
I just downloaded the new version of the NorthStar client but now when I open the game this is was I see:

![image](https://user-images.githubusercontent.com/69994588/164203358-410dcdfa-f2d0-460e-aa82-af5c835fdeab.png)

I tried everything on the troubleshooter and I tried to launch it through both the client and origin but it still didn't work.

**Comment by F1F7Y** [comment]
This means your game encountered a UI script error. Try deleting `R2Northstar` and reinstalling 1.6.3

**Comment by ItsTheRealAB** [comment]
> 

Tried that and it worked thanks a lot
