### ISSUE TITLE
Add CI logic to pull navmeshes during release build

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#263]
For including Attrition in 1.7 we need to also pull in the navmeshes while making release (candidate) builds.

**Comment by abarichello** [comment]
Implemented by: https://github.com/R2Northstar/Northstar/commit/02639ff6bdff48fb41009f4b9275118cd398ffc8
Example run: https://github.com/abarichello/Northstar/actions/runs/2239862942

**Comment by GeckoEidechse** [comment]
Completed with 4bd0a75b8224e2326f01cc33b38d98bbf014e3d0
