### ISSUE TITLE
Northstar crashing when it is loading.

### ISSUE THREAD

**Issue by snake2424** [R2Northstar/Northstar#28]
I launch the exe, and its mid loading (the titanfall 2 game it self doesn't launch) and boom it just disappears like my father.

**Comment by AyrO667** [comment]
![image](https://user-images.githubusercontent.com/96647631/147381077-3850940d-fc34-41d5-b7a9-725696d38304.png)

 what the problem could be?

**Comment by abarichello** [comment]
Can't leave this open if you don't provide us more info to debug, check https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting
