### ISSUE TITLE
AutoHDR disabled while using Northstar

### ISSUE THREAD

**Issue by mibarbic** [R2Northstar/Northstar#284]
### Bug
AutoHDR in Windows 11 does not activate when launching w/ Northstar and will only launch with vanilla TF|2.

### Steps to reproduce
  1. Run Northstar on any Windows 11 build with AutoHDR enabled in settings while using an HDR monitor.
 
### Specifications
  - Northstar version:  1.7.1.0
  - Platform: Origin

**Comment by GeckoEidechse** [comment]
What happens if you use `-northstar`? I.e. go to Origin, go to Titanfall2 properties, advanced settings, launch arguments, add `-northstar` and then launch Titanfall2.

**Comment by mibarbic** [comment]
I can confirm launching with `-northstar` resolved the issue.
Thank you, appreciate it!

**Comment by p0358** [comment]
Could be force-enabled by this: https://github.com/Choum28/AutoHDR

Northstar could add such a key to registry itself too presumably
