### ISSUE TITLE
(bug) Kamikazi-ing with a frag grenade crash 

### ISSUE THREAD

**Issue by R01lAttack** [R2Northstar/Northstar#287]
### Bug
Hitting someone with an overcooked frag grenade crashes

### Steps to reproduce

  1. Hold frag
  2. let it blow up in your hands
  3. be close enough to someone else to hit them as well

https://user-images.githubusercontent.com/78607129/170878319-5225dc6e-01ab-409a-8747-e07b85b03fdd.mp4

### Specifications
  - Northstar version:
  - Platform: Steam

**Comment by RoyalBlue1** [comment]
We couldn't recreate the issue. Do you have any mods installed?

**Comment by RoyalBlue1** [comment]
The bug is from HUDrevamp. There is a newer version of that mod that fixes that issue
