### ISSUE TITLE
Campaign stuck at loading screen

### ISSUE THREAD

**Issue by GabanKillasta** [R2Northstar/Northstar#288]
Same bug is back, as soon as i try to load the campaign it just stays at the beginning loading screen, no errors in the console, and im just stuck there, the only way out i can do is closing the game completely

**Comment by GeckoEidechse** [comment]
> Same bug is back

Can you reference the previous GitHub issue please? <3

**Comment by Zanieon** [comment]
Looks like this was a problem with old code, campaign nowdays works fine. Closing issue.
