### ISSUE TITLE
Feature request: button to cancel loading and return to the menu

### ISSUE THREAD

**Issue by Steveplays28** [R2Northstar/Northstar#29]
![image](https://user-images.githubusercontent.com/62797992/147373668-3263c455-3002-41b8-a846-1fb531701f27.png)
Say you're stuck loading like this, there should be a button to cancel loading and return to the menu.

The only option right now is to ~~alt+f4~~ open task manager and end the task, not exactly ideal.

**Comment by p0358** [comment]
You can always bind any key in a config file to "disconnect", preferably one of the top F1-F12 keys, adding a button would be harder than that

**Comment by VITALISED** [comment]
It may be possible to see what the vgui for the loading icon gets used. Perhaps after 7 seconds add a RUI button or something to where the menu is go to main menu

**Comment by emma-miler** [comment]
Unfortunately not possibly since the UI squirrel thread gets suspended during load.

**Comment by Steveplays28** [comment]
Damn, alright.
