### ISSUE TITLE
VCRUNTIME140_1.dll not found

### ISSUE THREAD

**Issue by SomerandomguyonGitHub** [R2Northstar/Northstar#299]
### Bug
Whenever I try to launch Northstar, I get a popup displaying the following message:
NorthstarLauncher.exe - System Error
The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem.
Long story short, it didn't.

### Steps to reproduce
I don't think this is happening for anyone else, but for me I simply launch the game and the message displays.

### Specifications
  - Northstar version: 1.8.0 (I think that's the newest version, because I've downloaded it like 3 times today)
  - Platform: Origin/Steam

**Comment by RoyalBlue1** [comment]
Have run the base game though steam at least once after install?

**Comment by TH3-S4LM0N** [comment]
Please use your brain
https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#vcruntime

**Comment by SomerandomguyonGitHub** [comment]
Thanks, I didn't know that I had to launch the base game first. In hindsight, it seems kinda obvious, but hindsight is 20/20. Foresight really isn't.

**Comment by SomerandomguyonGitHub** [comment]
Aaannd nevermind. I'm confused as hell because when I try to launch the vanilla game, i get a popup saying, "Failed to load the launcher DLL at "C:/Program Files (x86)/Steam/steamapps/common/Titanfall2/bin/x64_retail/tier0.dll": The specified module could not be found.
