### ISSUE TITLE
AI nav meshes

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [R2Northstar/Northstar#3]
(people have been linking this issue to people asking why attrition isn't selectable, so i'm editing to clarify)

AI nav meshes are required for any gamemode with AI, like Attrition, Frontier Defense, etc.

They were only stored on Respawn's servers, and Respawn isn't giving them up.

We need to re-create them ourselves.

----

**If you are a rogue Respawn dev about to give us the files:** Unless you have the full permission from your legal team, please don't; we could get sued for even looking at them. For this mod to be legal, we have to reverse-engineer it properly.

---

Apparently Titanfall 2 uses a custom format for nav meshes, and those are required for any gamemode with AI

We should, y'know, work on that.

**Comment by SIGSTACKFAULT** [comment]
in hindsight this should probably go in a different repo but i'm not sure which

**Comment by BobTheBob9** [comment]
so just to be clear here, Titanfall 2 has 2 core parts to navmeshes, there's [AIN files](https://developer.valvesoftware.com/wiki/AIN), though the format of these has been changed in some way to my knowledge, and navmeshes, which are based on [this](https://github.com/recastnavigation/recastnavigation), but also modified by respawn, both are needed for AI navigation to work correctly

**Comment by SIGSTACKFAULT** [comment]
do we need to make AIN files? Valve wiki implies that they're autogenerated.

**Comment by BobTheBob9** [comment]
nav_generate (the command used to generate ains) is removed in respawn source
to my knowledge, respawn generate theirs in level editor, not ingame like other source games do, so there's not much reason to keep it in, though there could be some other reason they don't include it

**Comment by p0358** [comment]
The code is stripped, the only chance for some maps for some time could be to port the AINs from TFO, depending how much the format has changed

**Comment by BobTheBob9** [comment]
TFO ains do work fine but ofc that's only on a couple maps, and without recast navmeshes ai will tend to lock up occasionally as well

**Comment by SIGSTACKFAULT** [comment]
~~I'm dumb, I thought AINs were generated from another file which was the actual navmesh~~

**Comment by SIGSTACKFAULT** [comment]
idea: make frontier defense work by just hard-coding enemy movement. possible?

**Comment by IncPlusPlus** [comment]
Are the AINs ever known by the client or does the client never get informed because the server is responsible for all the movement?

**Comment by BobTheBob9** [comment]
> Are the AINs ever known by the client or does the client never get informed because the server is responsible for all the movement?

client is never informed of actual ain data, they're only sent the movement of ai that uses it

**Comment by Erlite** [comment]
I wonder if they could make the AINs available. Northstar basically fixes the game for them, and once AI is back in, one way or another, they basically won't have to do anything anymore since custom servers are going to replace the official ones for sure.

**Comment by ASpoonPlaysGames** [comment]
So this could be completely wrong, but when I start up a server on, say, glitch, the server spews out a bunch of stuff about Path Nodes not having any links for hulls.

So I turned on cl_showpos 2 and noclip and flew around the map to the various coordinates given, and they seem to be the locations that the AI likes to stand around, I assume that the "no links for hulls" bit means that we basically have the points of the mesh, but we need to tell the AI how to go between the various points, right?


If so I think that would make our lives noticeably easier

(ive attached the server spew for Glitch if anyone is interested) [glitch path nodes.txt](https://github.com/R2Northstar/Northstar/files/7776303/glitch.path.nodes.txt)

**Comment by Erlite** [comment]
If this is correct, we know where the nodes are, but we'd still be unable to know which are linked to which, and it might even be auto-generated ones so not the real ones Respawn uses.

+ what Bob said about the Recast Navigation stuff.

**Comment by SIGSTACKFAULT** [comment]
> I wonder if they could make the AINs available. Northstar basically fixes the game for them, and once AI is back in, one way or another, they basically won't have to do anything anymore since custom servers are going to replace the official ones for sure.
> 
> It'd literally cost them less to just drop the AINs and have the community fix it for them.

legal would never let them do this.

even if a rogue respawn dev gave them to us, we couldn't look at them for fear of getting sued.

**Comment by Erlite** [comment]
One can hope it legally happens, it would be nice. Else, I guess we'll have to find a way to create our own for the maps.

**Comment by BobTheBob9** [comment]
just to make this clear, there's some work that's being done on this in the navmeshes thread in #research-and-development in the discord

**Comment by GeckoEidechse** [comment]
Uhm, given that we added Navmeshes with `v1.7.0`, I guess we can close this now :P
