### ISSUE TITLE
Servers say there full when there not

### ISSUE THREAD

**Issue by bxrdonut** [R2Northstar/Northstar#30]
Servers in the server browser above 9 or so people (from my tests) will give me an error that says "server is full". I was able to join servers that had like 2 people but plenty of half empty servers are unjoinable.

**Comment by shaybra** [comment]
@bxrdonut I've tested this and some servers that had 14 players were join able. I think the problem isn't that it's giving a "server is full" when it isn't, the problem might be that the server is actually full but the number of players wasn't updated.

**Comment by bxrdonut** [comment]
> @bxrdonut I've tested this and some servers that had 14 players were join able. I think the problem isn't that it's giving a "server is full" when it isn't, the problem might be that the server is actually full but the number of players wasn't updated.

yeah im starting to think that the player counters are broken

**Comment by MiloAkerman** [comment]
If there aren't plans to reduce server heartbeat delay this should prob be closed
