### ISSUE TITLE
Game crash mid game for no reason (that I know of)

### ISSUE THREAD

**Issue by RavMarv** [R2Northstar/Northstar#300]
### Bug
The game freezes then crashes mid game.

### Steps to reproduce
Haven't been able to replicate.

### Specifications
  - Northstar version: 1.8.1
  - Platform: Origin

### Logs
Here is the log: [nslog2022-06-22 14-34-50.txt](https://github.com/R2Northstar/Northstar/files/8957377/nslog2022-06-22.14-34-50.txt)
and here is the .dmp compressed to zip (if necessary):  [nsdump2022-06-22 15-05-14.zip](https://github.com/R2Northstar/Northstar/files/8957398/nsdump2022-06-22.15-05-14.zip)

**Comment by GeckoEidechse** [comment]
This issue is quite old. There's a decent chance this issue is no longer relevant or at least not feasible to reproduce at this point. As such I'm closing this as stale. Feel free to LMK if you still encounter this bug and re-open this GitHub issue or create a new one.
