### ISSUE TITLE
How to uninstall the mod?

### ISSUE THREAD

**Issue by scaryglue** [R2Northstar/Northstar#304]
### Bug
Because I want to play private matches with my friends without having to go through port forwarding and one of us having to set up a server, I tried launching the game without the mod, but to my knowledge, there is no way. Is there a way to disable the mod or uninstall without having to reinstall the whole game? I would love to still be able to access the server browser, but also create private matches without having to set up a server. When I try to launch the game normally through Steam, nothing happens, Origin just launches and closes itself. And when I try to launch the titanfall2.exe, Origin says "The game does not appear to be installed@.

### Steps to reproduce

  1. install the mod
  2. start the game normally through steam

### Specifications
  - Northstar version: 1.9.0
  - Platform:  Steam

**Comment by GeckoEidechse** [comment]
If you launch the game normally via Steam/Origin and do **NOT** have `-northstar` in your launch arguments it should just start vanilla.

To uninstall Northstar you simply delete the files and folders that you copied over from the release zip, i.e.

```
NorthstarLauncher.exe
launcher.dll
discord_game_sdk.dll
R2Northstar/
```

and then just verify game files in Steam/Origin.


If you're still having issues, please open a ticket on the [Northstar Discord](https://northstar.tf/discord). Issues on GitHub are use for bug reports etc, not tech support. ^^
