### ISSUE TITLE
I can't invite my friend to private match!

### ISSUE THREAD

**Issue by GrapplePilotTF2** [R2Northstar/Northstar#31]
Here's the story: "I just finished getting into the Northstar Client and my friend did too. Problem was, I could not invite him through Steam or Origin..." Is there a way you can fix this? :)

**Comment by SIGSTACKFAULT** [comment]
you need to [host a listen server](https://github.com/R2Northstar/Northstar/wiki/Hosting-a-Server), then tell your friend to connect to you by IP

**Comment by abarichello** [comment]
https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/direct-connect

**Comment by GeckoEidechse** [comment]
The [hosting prerequisites](https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar/prerequisites) and [listen server hosting instructions](https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar/basic-listen-server) are probably the best way to start.

As others have said, simply inviting someone via Steam/Origin does not work unfortunately.
