### ISSUE TITLE
Can't find servers

### ISSUE THREAD

**Issue by ChunkyPanda03** [R2Northstar/Northstar#32]
[nslog24-12-2021 20-05-10.txt](https://github.com/R2Northstar/Northstar/files/7775335/nslog24-12-2021.20-05-10.txt)

there is the log however I am getting an error when looking at the server list. The lines in particular are 
[2021-12-24 20:11:18.362] [info] Requesting server list from https://northstar.tf
[2021-12-24 20:11:18.801] [info] Got 28 servers
[2021-12-24 20:11:18.801] [error] Failed reading masterserver response: malformed server object

Not sure how this is happening I have opened up a server on the same computer and people are able to connect to me

**Comment by BobTheBob9** [comment]
please install [v1.1.1](https://github.com/R2Northstar/Northstar/releases/tag/v1.1.1) and let me know if this is still an issue

**Comment by ChunkyPanda03** [comment]
> please install [v1.1.1](https://github.com/R2Northstar/Northstar/releases/tag/v1.1.1) and let me know if this is still an issue

hey dude your an absolute legend keep up the good work. You probably posted the new launcher the moment I downloaded v1.1.0
