### ISSUE TITLE
LSX error

### ISSUE THREAD

**Issue by ngx200** [R2Northstar/Northstar#324]
### Bug
When I launch northstar (with and without the luncher viper) either the game does not launch or I get an LSX error.

### Specifications
  - Northstar version: 1.9.3
  - Platform: Steam (origine for the account)

![Capture d’écran 2022-08-14 191500](https://user-images.githubusercontent.com/109249188/184547782-5b1d4dc4-6a40-469a-8739-36d1648181fa.png)

**Comment by begin-theadventure** [comment]
**_Pinned_** issue..: https://github.com/R2Northstar/Northstar/issues/126
Wiki: https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#troubleshooting

**Comment by ngx200** [comment]
ok, thx
