### ISSUE TITLE
Server crashes when more than one player joins during first match

### ISSUE THREAD

**Issue by BLPFBisa** [R2Northstar/Northstar#33]
Quite self-explanatory from the title, I assume.
Whenever a second or more players try to join my server after a player successfully joined and started the first round after the server launched, the server will crash without an error.
After the first game has passed, people can freely join and leave the server without issues and the server operates smoothly.

Was tried with both game mode and playlist set to gg (Gun Game) and tdm (Skirmish) on Angel City, Colony and Glitch.

**Comment by TimeIsUnending** [comment]
I have a similar issue, but it's for dedicated servers, where when someone joins it just crashes the server.

**Comment by Jaco909** [comment]
Similar, also for dedicated. As soon as the **total** players hits 2, then it crashes. If one person leaves before the second authenticates, it's fine.  As soon as two players try to exist in the same server, then it will crash.
