### ISSUE TITLE
I dont know how to explain this issue

### ISSUE THREAD

**Issue by Jamesedward11** [R2Northstar/Northstar#345]
### Bug
I, uh... Well the game doesn't like it. I don't know how to describe this.

### Steps to reproduce

  1. Fresh Install TF|2 and Origin, and Play the game once
  2. Restart computer to refresh any packages or libraries
  3. Install Northstar with R2ModMan, might have something to do with the mods as well but i doubt it.
  4. see video

### Specifications
  - Northstar version: 1.9.7
  - Platform: Steam
  - Installed by R2ModMan

![image](https://user-images.githubusercontent.com/36340655/194441138-bc7f318a-e2c4-42e0-82c7-61ff0d293ca2.png)
![image](https://user-images.githubusercontent.com/36340655/194441152-c7a05423-5d29-4dc5-94a1-7cb872b4cad7.png)

https://user-images.githubusercontent.com/36340655/194441342-75e80480-8896-4ca2-bfc8-dd46dfbd181e.mp4
[nslog2022-10-06 20-14-26.txt](https://github.com/R2Northstar/Northstar/files/9729480/nslog2022-10-06.20-14-26.txt)

**Comment by Jamesedward11** [comment]
The video did not appear to post.

Uploading unknown_2022.10.06-20.13.mp4…

**Comment by ASpoonPlaysGames** [comment]
Looks like a classic audio override mod conflict crash to me

**Comment by ASpoonPlaysGames** [comment]
Yeah you installed the neon ion series, and didnt choose a single colour out of it, you have to only have 1 of the colours enabled at a time

**Comment by Jamesedward11** [comment]
how do i choose one then

**Comment by Jamesedward11** [comment]
This entire issue was caused by not having picked a colour?
how do i pick a colour then?

**Comment by ASpoonPlaysGames** [comment]
Open up your mods folder, and delete the colours that you no longer want, not 100% sure how to do that in r2modman tbh

**Comment by GeckoEidechse** [comment]
Closing as not directly related to core Northstar.
