### ISSUE TITLE
Some server's issue?

### ISSUE THREAD

**Issue by anotement** [R2Northstar/Northstar#354]
### Bug
Get these lines in console while in-game launching Northstar
[error] SERVER SCRIPT COMPILE ERROR Undefined variable "NSIsPlayerIndexLocalPlayer"
[error] _menu_callbacks.gnut line [12] column [33]
### Steps to reproduce

  1.Download and install new Northstar client
  2.Turn on the game
  3.Try to "Launch Northstar"

### Specifications
  - Northstar version:1.10.0
  - Platform: Steam

![Снимок](https://user-images.githubusercontent.com/116757704/198116035-da93bd64-2a3a-4723-988c-32990ed85d90.PNG)

**Comment by RoyalBlue1** [comment]
That function got removed changed with the latest update. You are either using a mod that has to be updated to the new function or you are using outdated core mods. 
Either remove or disable the mod in question or update core mods

**Comment by anotement** [comment]
Got the file like 10 minutes ago. Are you sure?

**Comment by GeckoEidechse** [comment]
@anotement update your game.
