### ISSUE TITLE
Clients getting disconnected with `sent too many stringcmds`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#358]
This seems to affect `v1.10.0` and higher with clients getting disconnected from servers with `sent too many stringcmds`. This does not appear to affect `v1.9.7`.

More investigation is needed.

**Comment by E3VL** [comment]
[nslog2022-10-28_23-24-56.txt](https://github.com/R2Northstar/Northstar/files/9892335/nslog2022-10-28_23-24-56.txt)

Client side log of the issue.
Client got disconnected after doing seemingly nothing.
Had them test multiple things, spectating for periods of time, dying in multiple ways, executions, getting melee'd, getting executed, etc.

**Comment by GeckoEidechse** [comment]
Should be fixed with https://github.com/R2Northstar/NorthstarLauncher/pull/315
