### ISSUE TITLE
Dedicated servers broken...

### ISSUE THREAD

**Issue by TimeIsUnending** [R2Northstar/Northstar#36]
Basically everytime I try to join my own server or someone trys to join my server it works fine until someone else joins. There's no error message and usually the person who joins second gets a infinite loading screen. The match works just fine for the solo person until another person joins. 

Here's the startup args I'm running : '+setplaylist ffa +mp_gamemode ffa +map mp_wargames +max_players 12 +pilot_health_multiplier 1.25 +boosts_enabled 1 +earn_meter_pilot_overdrive 0 +earn_meter_pilot_multiplier 0'

I haven't really changed anything else that would cause this to my knowledge besides the autoexec_ns_server.cfg which I changed the 'ns_should_return_to_lobby' to '0' which should make it where after the match ends it just goes straight to the next match. 

Any ideas on what could fix this or what could be happening? My ultimate goal is to make a few servers that are on gamemodes like FFA and CTF that rotate through different maps after each match ends.

**Comment by ChunkyPanda03** [comment]
to be fair about to start another issue issue request because I can't connect to my own server....

**Comment by TimeIsUnending** [comment]
> to be fair about to start another issue issue request because I can't connect to my own server....

If you have multiple maps put in the startup args, then it won't let you connect. Or if you are connecting from the same PC then that could be causing the issue

**Comment by ChunkyPanda03** [comment]
> 

yeah it is the same PC is that the issue?

**Comment by ChunkyPanda03** [comment]
I mean I see people running titanfall 2 on linux maybe I can get a dedicated server running on my server

**Comment by Rackover** [comment]
Hello, I'm running 1.4.0 (latest release at the time) and I have the same issue
First person connecting it works just fine, then anyone who connects after that gets infinite loading. The server also crashes on its own after about three or four minutes, without doing anything in particular. 

Why was the issue closed - is there a fix or was it fixed? I do not see a commit referenced
Have a nice day

`+setplaylist private_match +ns_server_name "Test server" +mp_gamemode ffa +map mp_eden `

**Comment by Rackover** [comment]
For anyone who stumbles upon this thread, the temporary fix i found is to **never** indicate a map in the launch arguments and to supply it later, by writing `map mp_eden` in the console for instance.

**Comment by hummusbird** [comment]
+map is currently unstable. Do not use it.
