### ISSUE TITLE
Can't connect to dedicated server running on my own computer

### ISSUE THREAD

**Issue by ChunkyPanda03** [R2Northstar/Northstar#37]
![image](https://user-images.githubusercontent.com/43187846/147376464-b4bff33f-f4fb-4371-a3e8-2630b4630b3e.png)
so I have a server that is currently full with 16 people however I can not join my own server.
It is running on the same machine that I am playing on it with so that may be an issue not sure.

**Comment by TimeIsUnending** [comment]
How did you get more than 1 person to be able to join it?

**Comment by ChunkyPanda03** [comment]
> How did you get more than 1 person to be able to join it?

idk bro just hit start

**Comment by ChunkyPanda03** [comment]
I mean it's sad I don't even get to play with them 😭

**Comment by SIGSTACKFAULT** [comment]
experiencing this issue, but because when i try to connect it times out.

**Comment by ChunkyPanda03** [comment]
> when i try to connect it times out.

the issue with mine is that it doesn't even show up on the browser

**Comment by TimeIsUnending** [comment]
> > when i try to connect it times out.
> 
> the issue with mine is that it doesn't even show up on the browser

you didn't port forward right

**Comment by ChunkyPanda03** [comment]
> > > when i try to connect it times out.
> > 
> > 
> > the issue with mine is that it doesn't even show up on the browser
> 
> you didn't port forward right

I mean it works I have 16/16 people but here is my port forwards

![image](https://user-images.githubusercontent.com/43187846/147377557-7c918f7f-7b12-4066-910d-a42a14ccdf2d.png)
![image](https://user-images.githubusercontent.com/43187846/147377567-747a19b9-e32f-49fc-b5e6-63c245cbe252.png)

**Comment by ChunkyPanda03** [comment]
I mean I think this is what the wiki wanted

**Comment by Vitorvlv** [comment]
I also can't connect to my own server, apparently there's already a few people in there, but I can't join, the connection times out.

**Comment by RomeoCantCode** [comment]
did you try; +net_usesocketsforloopback 1
or other workaround: open console on your game and connect to 127.0.0.1 or your LAN IP (dont forget :port)

**Comment by Vitorvlv** [comment]
For me I can only connect to my server if I do lan:ip from the main menu. Before we go to the northstar multiplayer. You have to enable allowing people without authentication to enter your server in the server configs.
