### ISSUE TITLE
Northstar crashes on launch using Linux

### ISSUE THREAD

**Issue by amy-521** [R2Northstar/Northstar#372]
### Bug
Trying to launch Northstar Launcher.exe, a wine popup appears saying "Error: failed reading origin path", after that the game is stuck in a loading screen until it crashes, with another popup saying "failed to initialize origin: the Origin installation couldn't be found", this points at an error caused by the new EA app

### Steps to reproduce
Launch Northstar Launcher.exe from the file manager

### Specifications
  - Northstar version: V1.10.6
  - Platform: Steam

**Comment by GeckoEidechse** [comment]
Does vanilla work? Also launching from file manager is not really recommended on Linux. Linux instructions can be found here: https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/playing-on-linux

**Comment by GeckoEidechse** [comment]
Closing this as stale. Feel free to re-open if you are still experiencing this issue.
