### ISSUE TITLE
Game crashes when clicking on Northstar option in the main menu

### ISSUE THREAD

**Issue by Kurapika-Kurta-HxH** [R2Northstar/Northstar#38]
Both in v1.0.1 and v1.1.1, I run the Northstar client and are able to get to the main menu. When I click on the Northstar option in the main menu, the game transfers to a loading screen while lowering to 10 FPS, loads for one minute, then proceeds to crash to desktop and opening the Origin app (no error pop-ups appear). I haven't heard anyone else have this problem and if it matters, I am on Steam.

**Comment by abarichello** [comment]
Can you retry on newest release?
