### ISSUE TITLE
The Enabling hook LoadLibraryExWHook doesn't work on rent remote windows servers

### ISSUE THREAD

**Issue by kevinchen320** [R2Northstar/Northstar#39]
![image](https://user-images.githubusercontent.com/96642460/147377487-5fc42d07-32e9-4f2d-bb81-003147a910f3.png)
i've got steam, origin and the full game installed on the server. as well as the 1.0.1 NorthStar.
i get this while trying to run r2ds.

**Comment by notbluu** [comment]
[Try the newer version](https://github.com/R2Northstar/Northstar/releases/tag/v1.1.1)

**Comment by TimeIsUnending** [comment]
You don't have enough CPU core dedicated to the server. You need at least 4 for Titanfall to work lmao

**Comment by kevinchen320** [comment]
oops
got it ill try

**Comment by kevinchen320** [comment]
![image](https://user-images.githubusercontent.com/96642460/147377891-fca22813-34ba-43fb-bba9-0a86ce9d2ad3.png)
is the server opend yet like this?
i cant type in commands

**Comment by kevinchen320** [comment]
still cant find this server on my PC

**Comment by notbluu** [comment]
Do you have the right ports forwarded?

**Comment by kevinchen320** [comment]
its a remote server and i set all ports in and out cleared

**Comment by kevinchen320** [comment]
Well sometimes people can find and join but after a few seconds the server just dissappears
the game itself would still run smoothly though?
I think me and the masterserver's connection might have a problem?

**Comment by FoverEric** [comment]
How did you solve it? I ran into the same problem.

**Comment by BobTheBob9** [comment]
> Well sometimes people can find and join but after a few seconds the server just dissappears the game itself would still run smoothly though? I think me and the masterserver's connection might have a problem?

this was fixed with [this](https://github.com/R2Northstar/NorthstarMasterServer/pull/5) pull request

**Comment by BobTheBob9** [comment]
oops didn't mean to close that, unless other issues are cleaned up now

**Comment by kevinchen320** [comment]
should i reply here?&gt;
we're using NorthStarCN and wolf has already fixed the auto-dissappear bug caused by some heartbeat issues. He should have already posted a request.
we worked to make the server pack smaller, deleting many sound/model/single player shit. Now one pack of delicated server is about 6.5GB.
and we also found a way to host multiple lobbies on the same server, just copy multiple copies of the 6.5GB server pack and change the&nbsp;ns_player_auth_port thing in&nbsp;autoexec_ns_server.cfg.
I'm not sure the CPU cost for no players has joined the CN servers yet, but we can see that the RAM usage of a single lobby is a little bit less than 2GB.
its very kind of you to do such work, and i hope it would all go well.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月26日(星期天) 凌晨1:17
收件人: ***@***.***&gt;; 
抄送: "#Data Not ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [R2Northstar/Northstar] The Enabling hook LoadLibraryExWHook doesn&#39;t work on rent remote windows servers (Issue #39)





  
Well sometimes people can find and join but after a few seconds the server just dissappears the game itself would still run smoothly though? I think me and the masterserver's connection might have a problem?
  
this was fixed with this pull request
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DuRouRou** [comment]
老铁你这是咋解决的
能告诉一下吗?是否需要额外的包?
感谢

**Comment by SIGSTACKFAULT** [comment]
> 老铁你这是咋解决的
> 能告诉一下吗?是否需要额外的包?
> 感谢

via google translate:

Lao Tie, how did you solve this?
Can you tell? Do you need an extra package?
grateful

**Comment by HK560** [comment]
8c server have the same issue

**Comment by mitchpk** [comment]
Having the same issue with a 4-core AMD Oracle Cloud instance, using [this docker image](https://github.com/pg9182/northstar-dedicated).

**Comment by GeckoEidechse** [comment]
I'm closing as _stale_. The initial issue was fixed a while back and all other issues mentioned in this thread should be split out into separate issues by the respective authors.
