### ISSUE TITLE
UI script errors caused by reloading mods

### ISSUE THREAD

**Issue by uniboi** [R2Northstar/Northstar#396]
### Bug
Infinite loop after resetting UI vm, crashing after a few seconds.

### Steps to reproduce
  1. Install n* 1.11.0
  2. reset UI vm (`uiscript_reset`)

### Specifications
  - Northstar version: 1.11.0
  - Platform: Steam, manual install
  
No mods installed.
[nslog2022-12-14 21-52-03.txt](https://github.com/R2Northstar/Northstar/files/10231610/nslog2022-12-14.21-52-03.txt)

**Comment by uniboi** [comment]
The PR that introduced tgis issue is [349](https://github.com/R2Northstar/NorthstarLauncher/pull/349)

**Comment by uniboi** [comment]
fixed in https://github.com/R2Northstar/NorthstarLauncher/pull/370

**Comment by emma-miler** [comment]
Fixed in https://github.com/R2Northstar/NorthstarLauncher/pull/370
