### ISSUE TITLE
prevent other people from editing custom match settings

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [R2Northstar/Northstar#4]
this is supposedly possible, just would require some work.

**Comment by ASpoonPlaysGames** [comment]
There are multiple ways that this could be implemented, I think the easiest option would be to have the player who has been in the lobby the longest get control over the match settings. It's not a perfect solution by any means, but a perfect solution would take a lot more work.

**Comment by pg9182** [comment]
https://github.com/R2Northstar/NorthstarMods/commit/15a37d022a4fb32f0d69ecd6eaa4894209b73c69

https://github.com/R2Northstar/NorthstarMods/blob/15a37d022a4fb32f0d69ecd6eaa4894209b73c69/Northstar.CustomServers/mod.json#L34-L42
