### ISSUE TITLE
Invalid Username Error for Titanfall 2 Campaign

### ISSUE THREAD

**Issue by HAVOC890** [R2Northstar/Northstar#402]

**Comment by james-amarth** [comment]
Open your in game console with `~` and type `ns_auth_allow_insecure 1`, then launch campaign.

**Comment by HAVOC890** [comment]
Where do you go to open the game console?


Where do u go to open the game console?

**Comment by HAVOC890** [comment]
WAIT I GOT IT THANK U SO MUCH

**Comment by ASpoonPlaysGames** [comment]
@HAVOC890 issue can probably be closed now
