### ISSUE TITLE
Show country information for servers

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/Northstar#41]
It would be quite useful to show country information for servers on the list, either in the description or the list.

This would involve:
- [ ] NorthstarMasterServer: Adding the MaxMind GeoLite2 database path to the server config and loading it on startup (possibly with the [maxmind](https://www.npmjs.com/package/maxmind) package)
- [ ] NorthstarMasterServer: Adding a field for the country based on the IP when a server is added
- Either:
  - Modifying the client to show the information separately
      - [ ] NorthstarLauncher: Parse the country information
      - [ ] NorthstarMods/Northstar.Client: Showing the country information in the server browser
  - Modifying the server to include the information in the existing fields
      - [ ] NorthstarMasterServer: Adding the country to the server name and/or description

@BobTheBob9, would you accept a PR for this, and if so, which approach would you rather take for showing the info?

**Comment by BobTheBob9** [comment]
i'm not 100% if i'd take a pr for this atm, not entirely certain, but for approach you'd likely want to just make another field in the server struct for it and add a new squirrel func for accessing it on client

**Comment by laundmo** [comment]
i definitely think the appropriate approach is making it a speprate field. as bob said, this requires a new field in the server struct and a new squirrel func, plus some updates to the serverbrowser squirrel.

i would be willing to contribute the c++ and Squirrel parts of this, as I've done basically the same already for https://github.com/R2Northstar/NorthstarLauncher/pull/29

@BobTheBob9 what is your reasoning for not wanting a PR for this currently?

**Comment by GeckoEidechse** [comment]
I started working on this now. It works by using GeoIP on gameserver IP and adding the geographic information to server list as `region` key. On client it's displayed in the in-game serverbrowser replacing the existing (unused) latency column.

- [ ] https://github.com/R2Northstar/NorthstarMasterServer/pull/84
- [ ] https://github.com/R2Northstar/NorthstarLauncher/pull/232
- [ ] https://github.com/R2Northstar/NorthstarMods/pull/479

**Comment by GeckoEidechse** [comment]
1 year later and this should be fully implemented since https://github.com/R2Northstar/Atlas/commit/f4fefa65ec1932056082d69d1bd827afbcb88174 on Atlas and [`v1.11.0`](https://github.com/R2Northstar/Northstar/releases/tag/v1.11.0) on client.
