### ISSUE TITLE
v1.11.4 Northstar " Northstar Launcher Error"

### ISSUE THREAD

**Issue by HAVOC890** [R2Northstar/Northstar#410]
### Bug
It puts up this pop-up when I try to use Northstar to run Titanfall 2. I want to be able to play Titanfall 2 running Northstar. Please someone help. I did not have this problem with the other versions.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:1.11.4
  - Platform: Steam

![Screenshot 2023-01-05 203940](https://user-images.githubusercontent.com/121575542/210931337-e0d6be2f-cbaf-45a1-b8ad-c910dd1290d0.png)

**Comment by GeckoEidechse** [comment]
Does vanilla Titanfall2 still work?

**Comment by HAVOC890** [comment]
no, it only works with NorthStar client

**Comment by HAVOC890** [comment]
please someone help me

**Comment by F1F7Y** [comment]
Send a screenshot of the files in `Titanfall2\bin\x64_retail\`

**Comment by HAVOC890** [comment]
if u mean the games files then here
![Screenshot 2023-01-08 163006](https://user-images.githubusercontent.com/121575542/211226475-cd1fba07-f7f1-4fb7-8880-4a03f25a7a9e.png)

**Comment by F1F7Y** [comment]
I meant this
![image](https://user-images.githubusercontent.com/64418963/211226593-75f011ab-3d93-4652-9dcb-f1dc920d2434.png)

**Comment by HAVOC890** [comment]
![Screenshot 2023-01-09 144125](https://user-images.githubusercontent.com/121575542/211422785-9f943ad0-89d2-4d86-abf0-faf40de542dd.png)
i think this is it

**Comment by HAVOC890** [comment]
can u help me?

**Comment by GeckoEidechse** [comment]
Yeah, there should be a lot more DLLs in there. I suggest repairing your game on Steam/Origin/EA App depending where you own it, then launch vanilla, and then try Northstar again.

**Comment by HAVOC890** [comment]
how do i repair my game?

**Comment by HAVOC890** [comment]
wait titanfall 2 works now i just uninstalled an reinstalled it
