### ISSUE TITLE
Problem Processing game logic

### ISSUE THREAD

**Issue by UrOnMyBlackList** [R2Northstar/Northstar#419]
1. loading r2modman
  2. automatic loads EA 
  3. automatic loads Titanfall2 NorthStar
  4. and this what happens after loading (see images)

### Specifications
  - Northstar version:
  - Platform: 

![Titanfall 2 1_27_2023 8_14_15 PM](https://user-images.githubusercontent.com/97210203/215234722-fec752c5-f42f-49a5-a74d-7027864ebfc0.png)

![Titanfall 2 1_27_2023 8_39_03 PM](https://user-images.githubusercontent.com/97210203/215234973-80cf9ca0-36f7-48cf-be88-95da607f24ba.png)

**Comment by Zanieon** [comment]
Whatever the game was trying to access in the first screenshot seems to come from a mod replacing the main menu of the game, line 876 in Northstar's version of this script has nothing related to "ExtrasMenu".
