### ISSUE TITLE
Dead players might not count to player count?

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#420]
![image](https://user-images.githubusercontent.com/40122905/215321133-f30b35fc-e049-441b-9e53-defc72e60631.png)

**Comment by Zanieon** [comment]
I've ran into this issue couple times myself with my listen server, the cause of this is when the client is connecting but hard crashes during their loading screen, leaving a ghost of themselves into server, eventually the server kicks them by timeout. So this is not really an issue with any logic, just how the game behaves when such scenario happens (as it is basically the same with pretty much any other game too).
