### ISSUE TITLE
Safe I/O memory leak

### ISSUE THREAD

**Issue by EladNLG** [R2Northstar/Northstar#435]
Original note:
```txt
side-note: this causes a leak? when a file is added to the map, it's never removed.
no idea how to fix this - because we have no way to check if there are other threads waiting to use this file(?)
tried to use m.try_lock(), but it's unreliable, it seems.
```

Supposedly to fix this we would have to implement stuff ourselves, and it's not that bad of a leak really, only affecting each *new* file that is read/written.
With that being said, I'm happy to approve regardless of this leak. If it turns out to be a larger issue than anticipated, someone else can make a PR to fix it.

_Originally posted by @ASpoonPlaysGames in https://github.com/R2Northstar/NorthstarLauncher/pull/404#discussion_r1131061781_

**Comment by EladNLG** [comment]
basically we'd have to make a custom mutex class with a `use_count` variable that tracks how many threads are waiting.

**Comment by EladNLG** [comment]
irrelevant, no longer an issue.

**Comment by GeckoEidechse** [comment]
Did we fix this in a PR? Or was it never an issue in the first place?
