### ISSUE TITLE
Feature Request: Dedicated Linux Servers for cheaper(free) cloud server hosts (If at all possible)

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [R2Northstar/Northstar#44]
So a lot of hosts for cloud servers online with near to full access run Linux and having the server code run on Linux would make it a lot easier to host more dedicated servers more easily.

Like you could potentially even host a server for free similar how you can do it with Minecraft on the [Oracle always free tier](https://blogs.oracle.com/developers/post/how-to-set-up-and-run-a-really-powerful-free-minecraft-server-in-the-cloud).

I am pretty sure you have more important stuff to focus on for now but this would really be a cool thing to happen. Or if someone finds a way to run the server using a CMD version of Proton then that would work as well.

**Comment by pg9182** [comment]
The Oracle always free tier will only work if Northstar is run under an emulator / recompiler in the ARM instances since the x86 ones aren't powerful enough.

For anyone looking at running it in a different cloud provider, beware of the bandwidth usage (seems to be ~5-15 Mbps for a full lobby depending on the game mode and other activity).

**Comment by EzioTheDeadPoet** [comment]
So I guess it will be even more complicated. 😔

**Comment by GeckoEidechse** [comment]
See #49 for a discussion on instructions for hosting on Linux.

**Comment by abarichello** [comment]
Try this: https://github.com/Legonzaur/northstar-server-headless/

**Comment by pg9182** [comment]
I've released my docker image: https://github.com/pg9182/northstar-dedicated.

BTW, hetzner seems to work well for dedicated servers, and it's on the cheaper side (it's not as cheap as some of the smaller ones, but it's cheaper than most of the big ones).
