### ISSUE TITLE
Too aggrieved

### ISSUE THREAD

**Issue by Peter11-1** [R2Northstar/Northstar#443]
![IMG_20230322_081839.jpg](https://user-images.githubusercontent.com/123917443/226770999-f56c358c-fd0f-4cae-a15c-974d1d7d8361.jpg)

**Comment by GeckoEidechse** [comment]
I'm sorry but I have no idea what this is about, closing as unrelated.

**Comment by pg9182** [comment]
I'm having a hard time understanding this too, but I believe they are complaining about players (on either Northstar or vanilla servers, I can't tell) using Northstar mods to gain an unfair advantage and claiming it's not cheating by always highlighting opposing players, disabling shake/flash on fire, using the Kraber scope for all weapons, or making the Volt laser always active for all weapons (we've seen this before in screenshots...). They are wondering if we can do anything to prevent Northstar from being used this way.

**Comment by Peter11-1** [comment]
I think a key point of this issue is to use the Polaris mod on official servers. In northstar and northstarcn, I&nbsp; think it's OK because most&nbsp; player who use mods when playing Northstar. But the official server is different from Polaris, where most players don't use mods. At the same level, then, mod users have a certain advantage over non-mod users on official servers. Not to mention those who use cheating mods to gain an advantage.&nbsp;
I wonder if there will be a tool, or in a future update, Northstar will delete the file that uses the Northstar mod on the official server when the player starts the game. This is the effective solution I've come up with so far. As for mods that severely affect the balance of the game, I think this problem will be difficult to solve.&nbsp; Talk about it later





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R2Northstar/Northstar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 凌晨3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R2Northstar/Northstar] Too aggrieved (Issue #443)





 
I'm having a hard time understanding this too, but I believe they are complaining about players (on either Northstar or vanilla servers, I can't tell) using Northstar mods to gain an unfair advantage and claiming it's not cheating by always highlighting opposing players, disabling shake/flash on fire, using the Kraber scope for all weapons, or making the Volt laser always active for all weapons (we've seen this before in screenshots...). They are wondering if we can do anything to prevent Northstar from being used this way.

**Comment by Peter11-1** [comment]
> 对不起，但我不知道这是关于什么的，以无关的方式结束。

Thank you for closing

**Comment by Peter11-1** [comment]
> what

I think a key point of this issue is to use the Northstar mod on official servers. In Northstar and NorthstarCN, I think it's okay to use mods because most player who use mods when playing Northstar and NorthstarCN. But the official server is different from Polaris, where most players don't use mods. At the same level, mod users have some certain advantages over non-mod users on official servers. Not to mention those who use cheating mods to gain an advantage.
I wonder if there will be a tool, or in a future update, Northstar will delete the file that uses the Northstar mod on the official server when the player starts the game. This is the effective solution I've come up with so far. As for mods that severely affect the balance of the game, I think this will be difficult to solve.  Talk about it later

**Comment by Peter11-1** [comment]
> I'm sorry but I have no idea what this is about, closing as unrelated.

I think a key point of this issue is to use the Northstar mod on official servers. In Northstar and NorthstarCN, I think it's okay to use mods because most player who use mods when playing Northstar and NorthstarCN. But the official server is different from Polaris, where most players don't use mods. At the same level, mod users have some certain advantages over non-mod users on official servers. Not to mention those who use cheating mods to gain an advantage.
I wonder if there will be a tool, or in a future update, Northstar will delete the file that uses the Northstar mod on the official server when the player starts the game. This is the effective solution I've come up with so far. As for mods that severely affect the balance of the game, I think this will be difficult to solve.  Talk about it later

**Comment by Peter11-1** [comment]
> I'm having a hard time understanding this too, but I believe they are complaining about players (on either Northstar or vanilla servers, I can't tell) using Northstar mods to gain an unfair advantage and claiming it's not cheating by always highlighting opposing players, disabling shake/flash on fire, viewing the loadouts of the opposing team by pressing tab, using the Kraber scope for all weapons, or making the Volt laser always active for all weapons (we've seen this before in screenshots...). They are wondering if we can do anything to prevent Northstar from being used this way.

I think a key point of this issue is to use the Northstar mod on official servers. In Northstar and NorthstarCN, I think it's okay to use mods because most player who use mods when playing Northstar and NorthstarCN. But the official server is different from Polaris, where most players don't use mods. At the same level, mod users have some certain advantages over non-mod users on official servers. Not to mention those who use cheating mods to gain an advantage.
I wonder if there will be a tool, or in a future update, Northstar will delete the file that uses the Northstar mod on the official server when the player starts the game. This is the effective solution I've come up with so far. As for mods that severely affect the balance of the game, I think this will be difficult to solve.  Talk about it later

**Comment by Peter11-1** [comment]
There are many ways to load a mod on an official server. The question is how many people know about these methods, since the one I proposed is only for people who don't understand mods.&nbsp;Otherwise, it has to be voluntary




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R2Northstar/Northstar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 上午8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R2Northstar/Northstar] this is a very serious problem (Issue #443)





  
I wonder if there will be a tool, or in a future update, Northstar will delete the file that uses the Northstar mod on the official server when the player starts the game.
  
This is absolutely pointless cause players can easily sidestep any client side methods if they wanted to.

**Comment by Peter11-1** [comment]
> > 不知道会不会有工具，或者在以后的更新中，北极星会在玩家开始游戏时删除官方服务器上使用北极星模组的文件。
> 
> 这绝对是毫无意义的，因为如果玩家愿意，他们可以轻松避开任何客户端方法。

**Comment by Peter11-1** [comment]
There are many ways to load a mod on an official server. The question is how many people know about these methods, since the one I proposed is only for people who don't understand mods.&nbsp;Otherwise, it has to be voluntary

**Comment by Peter11-1** [comment]
> 有很多方法可以在官方服务器上加载模组。问题是有多少人知道这些方法，因为我提出的方法仅适用于不了解模组的人。否则，它必须是自愿的

**Comment by Peter11-1** [comment]
There are many ways to load a mod on an official server. The question is how many people know about these methods？since the one I proposed is only for people who don't understand mods. Otherwise, it has to be voluntary



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 23, 2023 03:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [R2Northstar/Northstar] Too aggrieved (Issue #443)




 
I'm having a hard time understanding this too, but I believe they are complaining about players (on either Northstar or vanilla servers, I can't tell) using Northstar mods to gain an unfair advantage and claiming it's not cheating by always highlighting opposing players, disabling shake/flash on fire, using the Kraber scope for all weapons, or making the Volt laser always active for all weapons (we've seen this before in screenshots...). They are wondering if we can do anything to prevent Northstar from being used this way.

**Comment by GeckoEidechse** [comment]
Client side anti-cheat was attempted in NorthstarCN before and barely had an impact. Security through obscurity will never work...

**Comment by Peter11-1** [comment]
There's nothing i can do about that




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "R2Northstar/Northstar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 上午8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [R2Northstar/Northstar] this is a very serious problem (Issue #443)





 
Client side anti-cheat was attempted in NorthstarCN before and barely had an impact. Security through obscurity will never work...
