### ISSUE TITLE
Northstar updater

### ISSUE THREAD

**Issue by Redpoll2** [R2Northstar/Northstar#45]
When you start Northstar, it looks for a newer version. If it found, it updates itself with the player's permission.

**Comment by GeckoEidechse** [comment]
Related to [#2 on the NorthstarLauncher repo](https://github.com/R2Northstar/NorthstarLauncher/issues/2).

**Comment by 0neGal** [comment]
I've personally started working on a tiny app to launch, update and do various things related to Northstar, so if @BobTheBob9 doesn't wanna implement spend time on auto-updater, my app suffice. I don't think this is necessarily something that needs to be built into in-game Northstar. An official launcher akin to mine seems (imo) like the best option.

**Comment by Erlite** [comment]
> I've personally started working on a tiny app to launch, update and do various things related to Northstar, so if @BobTheBob9 doesn't wanna implement spend time on auto-updater, my app suffice. I don't think this is necessarily something that needs to be built into in-game Northstar. An official launcher akin to mine seems (imo) like the best option.

Please create an open source repo for your application, sharing the .exe isn't very healthy ^^

**Comment by Alystrasz** [comment]
There's already somebody who's working on this : https://github.com/wozniak/ns-updater

---

Stolen from Discord:
![unknown](https://user-images.githubusercontent.com/11993538/147395564-aa31e82e-7f69-4014-94fb-dc696b2c6b1f.png)

**Comment by Alystrasz** [comment]
And the issue belongs indeed to the Launcher, maybe this ticket should be closed in favor of https://github.com/R2Northstar/NorthstarLauncher/issues/2 ?

**Comment by 0neGal** [comment]
> Please create an open source repo

Oh ofc it'll be open source (GPLv3)

> There's already somebody who's working on this

Sounds amazing, personally, I was going more for a GUI approach, but I was also planning on making a tiny shell script to do the same, since I don't really want to use a GUI tool however I assume most would rather.

> maybe this ticket should be closed in favor of R2Northstar/NorthstarLauncher#2

Makes more sense to have it there, not to mention having it in one issue instead of 2...

**Comment by Alystrasz** [comment]
Let's discuss on https://github.com/R2Northstar/NorthstarLauncher/issues/2 then :)
