### ISSUE TITLE
Sometimes, players can't join anymore after a disconnection

### ISSUE THREAD

**Issue by Legonzaur** [R2Northstar/Northstar#450]
# Bug
Sometimes, after disconnecting or being disconnected, players encounter an issue where they can't rejoin the server anymore.
The error players see is `Connection to server timed out` whenever they try to join the server they got disconnected from.
Joining other servers works fine. Restarting the client doesn't solves this issue.

This issue can last from 20 minutes to around 1 hour. Afterwards, the player can rejoin the server again

![image](https://user-images.githubusercontent.com/34353603/230563813-cb0c8ffb-988f-4d8e-b49f-e40ebc0d7684.png)

# More details
This issue started to arise when Fvnkhead updated his servers to [`1.12.4`](https://github.com/R2Northstar/Northstar/releases/tag/v1.12.4). When I talked about it on Discord, it seemed that some other servers are also concerned, in particular Neinguar's servers.

While this can happen after being kicked out with the message `Disconnect: Sent too many stringcmd commands.` from #448, this can also happen when retrying to disconnect and reconnect from the server because of #449 

I had some results trying to continue to play by switching between 4G and ADSL whenever the server didn't wanted me to join again, until I ultimately was unable to join with both internet connections.

**Comment by GeckoEidechse** [comment]
Wait so getting disconnected from a server due to `Disconnect: Sent too many stringcmd commands.` completely prevents you from rejoining for extended periods? o_O

I would expect that due to the circumstance of the disconnect, one would be unable to rejoin until fully timed out on the server but that should be like 1 minute top, not 20+. Could be that it coincides with map change...? Hmm....

**Comment by NoCatt** [comment]
2 confirmed cases where the users had the lastest version, the issues seems to be fixed at random.

**Comment by ASpoonPlaysGames** [comment]
Sounds to me like the server is making client send a number of stringcmds on connect, and that number is increasing somehow?
Map change sounds like the reason for it stopping though.

I have a suspicion, I'll look into it properly in a bit

**Comment by Legonzaur** [comment]
> Wait so getting disconnected from a server due to `Disconnect: Sent too many stringcmd commands.` completely prevents you from rejoining for extended periods? o_O
> 
> I would expect that due to the circumstance of the disconnect, one would be unable to rejoin until fully timed out on the server but that should be like 1 minute top, not 20+. Could be that it coincides with map change...? Hmm....

This issue in particular can also happen **after manually disconnecting from the server**

**Comment by Legonzaur** [comment]
As far as I tested, this doesn't occurs in `1.12.3`

**Comment by GeckoEidechse** [comment]
> As far as I tested, this doesn't occurs in `1.12.3`. Only `1.12.4`

Huh, ngl I didn't expect. If you don't mind, running `v1.12.3` over the weekend and checking for player feedback could help a lot in debugging this issue :eyes:

**Comment by Legonzaur** [comment]
Problem resolved after #447 and/or `v1.12.5`
