### ISSUE TITLE
Sonar is stuck.

### ISSUE THREAD

**Issue by SmSmKun** [R2Northstar/Northstar#47]
When someone pulses a sonar, it's stuck till the end of the game and I become glowing orange indefinitely.

**Comment by SIGSTACKFAULT** [comment]
Could you record a video of the bug happening?

**Comment by abarichello** [comment]
Not sure what you are talking about, both sonar blade and sonar pulse seem to be working as intended

**Comment by x3Karma** [comment]
only happening on map hack

**Comment by abarichello** [comment]
https://github.com/R2Northstar/NorthstarMods/issues/23
