### ISSUE TITLE
Attrition server crashing since `v1.13.0`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#483]
According to server hosts, `v1.13.0` and higher servers seem to be crashing after some time on Attrition.

Last known stable is `v1.12.7`

Logs contain no info

Seems to affect both Docker and Windows

Direct link to public Discord thread on Northstar Discord: https://discord.com/channels/920776187884732556/1102549195958796339/1103027612437196840

**Comment by GeckoEidechse** [comment]
Apparently can be triggered easily by

> literally just sitting in attrition going round killing AI
> nothing like
> specific
> i just thought it would be a rarer issue but yeah

( via @ASpoonPlaysGames )
https://discord.com/channels/920776187884732556/1102549195958796339/1105964709338939442

**Comment by EnderBoy9217** [comment]
@GeckoEidechse This issue is still pinned BTW, despite being fixed

**Comment by GeckoEidechse** [comment]
Fixed issue can stay pinned if they are still relevant. That being said, we are since version gating way above the release that fixed it, so this issue is not longer relevant.

So thanks for bringing it to my attention <3

Unpinned.
