### ISSUE TITLE
Linux: Failed reading Origin path!

### ISSUE THREAD

**Issue by Byt3Size** [R2Northstar/Northstar#486]
### Bug
When launching the NorthstarLauncher executable using `wine`, an error message window with `Error: failed reading Origin path!` appears, while it is supposed to launch normally.

### Steps to reproduce
  1. Use `wine ~/.local/share/Steam/steamapps/common/Titanfall2/NorthstarLauncher.exe` in a terminal emulator

### Specifications
  - Northstar version: 1.14.0
  - Platform: Steam
  - OS: Nobara Linux 37 (64-bit)
  - Processor: 11th Gen Intel Core i3

**Comment by Alystrasz** [comment]
You cannot run the Northstar executable directly, you need to setup some stuff beforehand. 
Linux instructions: https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/steamdeck-and-linux/installing-on-steamdeck-and-linux
