### ISSUE TITLE
Linux release for the servers

### ISSUE THREAD

**Issue by Vitorvlv** [R2Northstar/Northstar#49]
Opening this since #1 was closed.

Servers are usually hosted on linux machines. A linux release for the server portion would be welcomed, having to go through wine is not exactly ideal, and I'm not sure if it even works.

**Comment by PixieCore** [comment]
It has to run under wine unless you feel like reversing the whole server part. Game doesn't exist on linux so no native compilation for it.

**Comment by Kuratius** [comment]
@PixieCore from what I understand, reimplementing the server is exactly what this project did.

**Comment by PixieCore** [comment]
@Kuratius No wrong, it made it properly work. FULLY REBUILDING IT. Is another story.

**Comment by BobTheBob9** [comment]
> @PixieCore from what I understand, reimplementing the server is exactly what this project did. Squirrel can run on linux.

this project hooks the existing game client to host servers, it doesn't rebuild the server from scratch, tho it does rebuild alot of missing gamelogic, a native linux port would require reverse engineering a significant amount of code that only respawn has access to, so a native port is likely out of the question

**Comment by Kuratius** [comment]
@BobTheBob9 Could you reopen this? Even if a non wine release is not possible, ensuring it runs smoothly under wine (especially headlessly) would already be a great boon.

**Comment by pg9182** [comment]
For the record, I have successfully run a dedicated server (~1840 MB RAM, ~110ms CPU time on a Ryzen 5 3500U) on Fedora 35:

- ext4 filesystem (I've had issues with other ones -- ntfs3 seems to work most of the time, but I've had tf2 complain about corrupted files a few times; overlayfs has the same issue unless it's backed by ext4)
- Titanfall 2 (copied game files, not even fully installed)
- Northstar v1.1.2
- Mesa 21.3.2 (distro packages)
- Wine 7.0.0-rc2 (distro packages)

```bash
export HOME=$PWD
export WINEARCH=win64
export WINEPREFIX=$HOME/Wine
export LIBGL_ALWAYS_SOFTWARE=1
export WINEDEBUG=-all
cp Titanfall2/NorthstarLauncher.exe Titanfall2/Titanfall2.exe
wine Titanfall2.exe -dedicated -multiple
```

DXVK must NOT be used since we want to use llvmpipe for software rendering via wined3d, and since WARP isn't supported on anything but Windows, we can't use `-softwared3d11`.

I am going to

**Comment by GeckoEidechse** [comment]
I'm working on a wiki for Northstar at the moment whose content will hopefully be moved into the official Northstar wiki in the future.

I added a [section for hosting dedicated servers on Linux](https://gecko-eidechse-gitbook.gitbook.io/r2northstar/hosting-a-server-with-northstar/dedicated-server#hosting-on-linux), would be great if someone that managed to get it working could add the necessary steps via pull request [on the repo linked to the gitbook](https://github.com/GeckoEidechse/Northstar-wiki/blob/master/hosting-a-server-with-northstar/dedicated-server.md#hosting-on-linux).

**Comment by EzioTheDeadPoet** [comment]
> I am going to see if I can reduce the installation size, then try packaging it in a Docker container, then try to get it to run under emulation or dynamic recompilation on ARM.

Please once you figured this out @ me on the post where you did it.

I am really really hyped for this.

**Comment by Legonzaur** [comment]
I managed to create a docker image running headlessly using lavapipe+dxvk+wine with the help of @pg9182's work
https://github.com/Legonzaur/northstar-server-headless

**Comment by pg9182** [comment]
Speaking of which, I'm working on a more polished container in [pg9182/northstar-dedicated](https://github.com/pg9182/northstar-dedicated), where I also have collected many of my notes on running the NS dedi on Linux.

**Comment by Hacker1245** [comment]
> I am going to see if I can reduce the installation size, then try packaging it in a Docker container, then try to get it to run under emulation or dynamic recompilation on ARM.
Maybe you could try to run Northstar via FEX or box64?

**Comment by pg9182** [comment]
I have published my container.

> Maybe you could try to run Northstar via FEX or box64?

@r3muxd tried this: FEX is too slow, and box64 is currently missing an opcode.

**Comment by Hacker1245** [comment]
@r3muxd on what device did you try that?

**Comment by pg9182** [comment]
Oracle ARM

**Comment by Hacker1245** [comment]
What CPUs do they have?

**Comment by EzioTheDeadPoet** [comment]
@Hacker1245 Ampere 3.0 GHz Ampere Altra 80C.

2-4 Cores on the free tier.

**Comment by Hacker1245** [comment]
that should run x64 emulation fine, so it's FEX not being fully optimized yet. Wonder how box64 will do once the unimplemented opcode is fixed.

**Comment by pg9182** [comment]
Yes, it should be fine with box64's recompilation; it's pretty fast (I use it as a build server and a remote desktop).
