### ISSUE TITLE
Vanilla via NorthstarLauncher spams logs on `v1.14.2`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/Northstar#492]
### Bug
Launching `NorthstarLauncher.exe` without mods, e.g. `NorthstarLauncher.exe -norestrictservercommands -profile=R2Vanilla` and `R2Vanilla` is an empty folder results in console and logs being spammed with 

```
[22:15:54] [SCRIPT CL] [error] Call was unable to find function with name 'NorthstarCodeCallback_GenerateGameState'. Is it global?
[22:15:54] [SCRIPT UI] [error] Call was unable to find function with name 'NorthstarCodeCallback_GenerateUIPresence'. Is it global?
```

### Steps to reproduce
  1. Launch Northstar with no mods
  2. Play some Attrition match I guess (although it should already start happening in `mp_lobby`
  3. Check your console and/or logs

### Specifications
  - Northstar version: `v1.14.2`
  - Platform: Steam

[nslog2023-06-11 22-13-13.txt](https://github.com/R2Northstar/Northstar/files/11715657/nslog2023-06-11.22-13-13.txt)

**Comment by GeckoEidechse** [comment]
@catornot ideas? 👀

**Comment by F1F7Y** [comment]
This gets called from:
https://github.com/R2Northstar/NorthstarLauncher/blob/9cf27a61fd7e096f816c512375ef2340ea4dfb10/NorthstarDLL/shared/gamepresence.cpp#L40

imo the best option would be to have a `-vanilla` launch arg for playing on vanilla which could then disable northstar specific behavior like this. Would first need to remove `-vanilla` check from NorthstarLauncher ( here https://github.com/R2Northstar/NorthstarLauncher/blob/9cf27a61fd7e096f816c512375ef2340ea4dfb10/NorthstarLauncher/main.cpp#L259 ) which currently does nothing

**Comment by catornot** [comment]
ask vanilla people to remove discord rpc plugin 
simple solution

**Comment by GeckoEidechse** [comment]
> ask vanilla people to remove discord rpc plugin
> simple solution

It still shows up even without DiscordRPC plugin from what I tested.

**Comment by F1F7Y** [comment]
> It still shows up even without DiscordRPC plugin from what I tested.

Yup, because it's called from `Northstar.dll`

**Comment by catornot** [comment]
Oh right I forgor
I will move that functionality to the plugin instead of the plugins system in plugins v3 so it shouldn't be an issue in the future

**Comment by begin-theadventure** [comment]
The error happens since version v1.13.0,  v1.12.7 is fine.

**Comment by begin-theadventure** [comment]
Only Northstar.dll needs to be replaced to stop spamming.

**Comment by GeckoEidechse** [comment]
Should be fixed by plugins v3 I think (haven't confirmed yet)
