### ISSUE TITLE
Phase Shifting right as you eject causes an error

### ISSUE THREAD

**Issue by Nemmysis** [R2Northstar/Northstar#495]
### Bug
Using phase shift the moment you eject causes you to get booted out of the server, footage and error displayed below.
Tested with Ion and Ronin.

### Steps to reproduce
  1. Enter your titan
  2. Eject/Self Destruct
  3. Hit the Phase Shift _just_ as you go back into pilot mode (Spamming the button usually works, but it may take a few attempts)

### Specifications
  - Northstar version: 1.14.3
  - Platform: Steam
 
![image_2023-06-18_165032018](https://github.com/R2Northstar/Northstar/assets/39452760/de15251f-a1f2-4245-a399-9a15ae7b2edc)

https://github.com/R2Northstar/Northstar/assets/39452760/af9d6d90-330d-4e4e-9dfa-e3719abb5e97

**Comment by ASpoonPlaysGames** [comment]
I believe that this is actually a bug with HudRevamp

**Comment by Nemmysis** [comment]
> I believe that this is actually a bug with HudRevamp

After testing with Ion and Ronin without HudRevamp, this seems to be the case, thanks
I will make sure to report this to them
