### ISSUE TITLE
11th gen intel processors are incompatible

### ISSUE THREAD

**Issue by Orifan1** [R2Northstar/Northstar#5]
we figured it out. its an incompatibility with AES-IN. 
below is the original post

///it leaves absolutely no error whatsoever
you click on a server, console says you're being authenticated aaaaaand... nothing
here's what I myself have tried specifically so far:
port forwarding the 8081 TCP
checking the master server hostname 
checking for any vpk mods
refreshing/restarting server list, game lobby, game itself, steam, origin, and whole PC
re-agreeing to the authentication agreement
disabling firewall
[message.txt](https://github.com/R2Northstar/Northstar/files/7773037/message.txt)

attached file is my logs. sorry i couldnt have them be fancily displayed or anything, im not used to github

**Comment by Aygent** [comment]
one thing to note, this could be a possible issue is that you get "Showing user info for UID 0 on hardware" a number of times after clicking on a server. 
![image](https://user-images.githubusercontent.com/48607462/147374279-b5233e60-c66a-4793-8321-59a8d81f4d0a.png)

**Comment by BobTheBob9** [comment]
> one thing to note, this could be a possible issue is that you get "Showing user info for UID 0 on hardware" a number of times after clicking on a server.
the UID 0 message should be unrelated to this, it's generated by the communities UI, not northstar code

**Comment by Orifan1** [comment]
is it possible this is related to error 4? i noticed im getting that, but most of the people i see talking about error 4 are people trying to host their own servers

**Comment by Davidththird** [comment]
following this post https://www.reddit.com/r/PavlovGame/comments/n3hllx/workaround_for_crash_on_launch_bug_for_11gen/ make it work for whatever reason

**Comment by Orifan1** [comment]
i dont have a gen 11 processor. are you sure it'll work?

**Comment by Orifan1** [comment]
ok apparently i do have an 11th gen processor. sorry about that, was unaware.

**Comment by GeckoEidechse** [comment]
For anyone coming across this issue make sure to [check this section in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#issues-with-newest-intel-cpu-10th+-gen) that explains what you need to do to run Titanfall|2 on 10th+ gen Intel CPUs.
