### ISSUE TITLE
Server disappears from server list if player count is 0

### ISSUE THREAD

**Issue by RomeoCantCode** [R2Northstar/Northstar#50]
Might be since version 1.1.1 or 1.1.2.
If you immediately join after server creation, it won't disappear and allows other players to join using the server list.

**Comment by TimeIsUnending** [comment]
I get the same thing with my server, sucks because it won't go up at all at this point because of this...

**Comment by MetalfaceScout** [comment]
I could be running into this issue. I'm trying to run a server and it only stays on the master server list for around 10 seconds.

**Comment by RomeoCantCode** [comment]
Only workaround I found so far:
Create an Autohotkey script that reads the window title and restart it every minute if it says "mp_lobby 0/16 "🤡
makes server visible 25% of the time all the time.

**Comment by BobTheBob9** [comment]
this has been fixed with [this](https://github.com/R2Northstar/NorthstarMasterServer/pull/5) pull request, should be on main masterserver soon
