### ISSUE TITLE
`MilesLog` spams logs freezing up the game

### ISSUE THREAD

**Issue by F1F7Y** [R2Northstar/Northstar#509]
[`MilesLog`](https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDLL/client/audio.cpp#L497) a logging function used by miles can sometimes log so much that it freezes the game.

The logging it-self is intended behavior. Whether our changes cause it to fail some check and spam logs is unknown.
Either way we should add a cvar to toggle this just like we do with `spewlog_enable`

**Comment by ASpoonPlaysGames** [comment]
Should probably be moved to NorthstarLauncher?
