### ISSUE TITLE
encounteert server script compilation error

### ISSUE THREAD

**Issue by noahn1233333** [R2Northstar/Northstar#519]
### Bug
Replace this line with the bug you've encountered and what is the expected behaviour.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by uniboi** [comment]
Please attach a logfile with the error or open a ticket in the [discord](https://discord.com/northstar)

**Comment by GeckoEidechse** [comment]
Closing as stale
