### ISSUE TITLE
problems connecting to the data centers

### ISSUE THREAD

**Issue by Arkathomp** [R2Northstar/Northstar#52]
![2021-12-25](https://user-images.githubusercontent.com/60485352/147392424-52722bbf-0520-44a1-ad6e-ced8e6585a6d.png)
![2021-12-25 (1)](https://user-images.githubusercontent.com/60485352/147392429-c5239721-1e01-4d34-9b02-59bcdec3aab0.png)

**Comment by SIGSTACKFAULT** [comment]
Do you own TTF2 legitimately?

**Comment by Arkathomp** [comment]
yes, the problem is with northstar i think

**Comment by GeckoEidechse** [comment]
Does this also happen on vanilla client? Do you have a 10th+ gen Intel CPU?

**Comment by rc088** [comment]
I had the same problem on my new PC.  I'm running 11th Gen Intel(R) Core(TM) i7-11700F and found a solution using these links: 
https://www.reddit.com/r/titanfall/comments/kpnlef/contacting_respawn_servers_cannot_play_multiplayer/?sort=top
https://www.valuewalk.com/2019/11/if-pubg-crashes-on-your-intel-ice-lake-processor-try-this/

>     Press Win + E or open File Explorer, right-click on “This PC,” and choose “Properties.
>     Click on “Advanced System Settings.”
>     Under the Advanced tab, choose “Environment Variables.”
>     Under “System variables,” click on “New.”
>     In the “Variable name” box, type this: OPENSSL_ia32cap
>     In the “Variable value” box, type this: ~0x200000200000000
>     Then click on “OK.”
>     Confirm the addition of the variable to the “System variables” list and choose “OK.”
>     Restart computer


From what I gathered this is an issue with the 11th Gen Intel CPUs
https://www.reddit.com/r/PavlovGame/comments/n3hllx/workaround_for_crash_on_launch_bug_for_11gen/

> This one really isn't Intel's fault. It's a bug in other software (OpenSSL) that was fixed way in 2017. Unreal Engine is still using a version of OpenSSL from 2016, though. Until Unreal Engine updates, and then PUBG updates, there's no other alternative.
> 
> The reason the bug only shows up on new processors is because OpenSSL tries to take advantage of bleeding-edge options on the newer processors to go faster. But, they had a mistake and used those bleeding-edge options wrong. Those new options only showed in the 11th gen, which is why it didn't cause problems until now.

**Comment by Arkathomp** [comment]
i acctually have ryzen, and my proplem fixed its self but thanks for trying to help
