### ISSUE TITLE
how tf do you update the game

### ISSUE THREAD

**Issue by titanbetter** [R2Northstar/Northstar#525]
### Bug
Replace this line with the bug you've encountered and what is the expected behaviour.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by CooldudePUGS** [comment]
use a [mod manager](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/northstar-installers) to do it automatically

or follow the [guide to manually install/update](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/manual-installation) (installing and updating manually have the same process)

**Comment by uniboi** [comment]
manually installing anything is heavily discouraged. Use [flightcore](https://github.com/R2NorthstarTools/FlightCore) to install the launcher and mods

**Comment by GeckoEidechse** [comment]
Not a bug/feature-request, closing.
