### ISSUE TITLE
Crash on missing `packages` directory

### ISSUE THREAD

**Issue by ZeroDayCartel** [R2Northstar/Northstar#528]
I can't find anything regarding this problem but the console gives me an error on launch of a fresh install of both Northstar and Titanfall. I've included the full log.
[Northstar Error 1-17-1-0.txt](https://github.com/R2Northstar/Northstar/files/12206349/Northstar.Error.1-17-1-0.txt)

**Comment by CooldudePUGS** [comment]
create an empty folder called `packages` in `titanfall2/r2northstar`, then try again

**Comment by ZeroDayCartel** [comment]
It works. Thank you.

**Comment by GeckoEidechse** [comment]
Caused by https://github.com/R2Northstar/NorthstarLauncher/pull/513 and resolved with https://github.com/R2Northstar/NorthstarLauncher/pull/523 which is released in `v1.17.2`
