### ISSUE TITLE
Issue triage

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/Northstar#55]
The issue tracker is currently a mess, and it'll only get worse over time. Most issues are just being filed here along with suggestions and troubleshooting, and issues are also being filed in other repos, often the wrong ones (e.g. an issue about game modes was just opened on the launcher repo rather than the mods repo).

**Comment by pg9182** [comment]
Some ideas:
- Labels.
- Issue templates (with labels too).
- Either removing the issues tab from other repos (like the way Go does it), or making clear guidelines of where things go.
- Either requiring all troubleshooting to be on Discord or to use GitHub discussions for it.

**Comment by Alystrasz** [comment]
There's already some notes about where things go there: https://github.com/R2Northstar/Northstar, but I suppose it's not clear enough for neophytes.
Let me write some contributions documentation :)

**Comment by abarichello** [comment]
We're working on it. Thanks
