### ISSUE TITLE
[Dedicated Server] Failed authenticating with server

### ISSUE THREAD

**Issue by TheRealKamisama** [R2Northstar/Northstar#57]
I was able to host a working dedicated server on my local machine.  
It all checked out and showed in Server Browser.  

When I transfered it to my Windows Server this showed up.  
The Server is under the same network environment as my local machine.  
`[error] Failed authenticating with server: error httplib::Error::SSLServerVerification.`  
It used to be `[error] Failed authenticating with server: error 10.` in older version of northstar.  

I tried reinstall northstar and verified Titanfall2 with Origin.  

Can't find any solution to this in neither discord channel nor github issue, would you tell me what this is?

**Comment by DitaSoft** [comment]
Same problem here.

**Comment by TheRealKamisama** [comment]
Updated to v1.2.2 and its gone 👍
