### ISSUE TITLE
I'm trying to build a server. I need help

### ISSUE THREAD

**Issue by DuRouRou** [R2Northstar/Northstar#58]
I put the module on the window server and only output these contents after startup
我将模组放在WinServer,启动只输出了这些内容
[17:32:27] [info] Enabling hook LoadLibraryExAHook
[17:32:27] [info] Enabling hook LoadLibraryExWHook
I would like to ask whether the whole game ontology is needed to start the server?
我想知道是否需要游戏本体来启动服务端
Or more packets are needed?
或者是需要更多的数据包?

**Comment by Bandesss** [comment]
Yes you musst Origin or Steam in you Windows Server

**Comment by ABAxStorm** [comment]
Your Windows Server must have at least 4 vCores, upgrading just fixed that issue for me.

**Comment by abarichello** [comment]
Join the discord if you need help setting up servers
