### ISSUE TITLE
How to write/customize the playlist of a lobby?

### ISSUE THREAD

**Issue by kevinchen320** [R2Northstar/Northstar#61]
there is this 'ns_should_return_to_lobby 1' so i assume it would be a way to customize the playlist of my lobby
and set it to 0 to make the server repeat the playlist without players in the lobby changing the lobby settings by them self

but how to make a playlist? the guide in wiki seemed not have it mentioned..

**Comment by abarichello** [comment]
Check the discord if you need help setting up your selver, or fill an issue on https://github.com/R2Northstar/NorthstarWiki for specific tutorials
