### ISSUE TITLE
"Launch Northstar" option locked and News menu not visible on Steam

### ISSUE THREAD

**Issue by KnyghtLake** [R2Northstar/Northstar#63]
![image](https://user-images.githubusercontent.com/41136748/147437730-99ae906c-0646-4878-a75e-033917a91972.png)

**Comment by 334431** [comment]
I usually wait and it unlocks, check if your connection is slow or just try restarting

**Comment by abarichello** [comment]
This is probably due to connection/server issues. Let us know if it keeps happening consistently
