### ISSUE TITLE
Disabling the timelimit

### ISSUE THREAD

**Issue by jamesla** [R2Northstar/Northstar#641]
I'm trying to find the command to disable the timelimit.

I've checked the wiki, asked in the discord and tried a bunch of stuff that chatgpt recommended but struggling.

Is this possible? If so, how can I find the config option?

**Comment by GeckoEidechse** [comment]
Just to be clear, you meant the match time limit, right?

**Comment by jamesla** [comment]
> Just to be clear, you meant the match time limit, right?

Yep

**Comment by GeckoEidechse** [comment]
Given that the game was never meant to run indefinitely, even the "24/7" servers have a time limit of ~1 hour and then restart the game on the same map.

At least from experience we noticed a bunch of weird behaviour for servers that are running on the same match for multiple hours (don't remember the exact details, it's been a while).

So I don't think we even have a way to disable the timelimit. Depending on what you are trying to achieve, you might instead just want to set a decently high timelimit and the map rotation to just that specific map ^^

**Comment by catornot** [comment]
There is a squirrel function for this that is used by FD.

**Comment by jamesla** [comment]
1 hour time limit would be fine - how would I configure that?

**Comment by Zanieon** [comment]
`timelimit` playlistvar can be used to set time to an extensive value in minutes.
