### ISSUE TITLE
ConVar ns_is_modded_server

### ISSUE THREAD

**Issue by delucax99** [R2Northstar/Northstar#642]
### Bug

Hello to whoever might be looking at this, hope you're doing well! :D

I updated Northstar to the newest `v1.24.4` & everything worked perfectly fine as it always has, until when trying to connect to the Northstar servers, I started encountering this problem.

I checked & rechecked all installed mods, all were up to date & after some digging, I found that "ModSettings" by EladNLG was deprecated. Thinking this might fix my problem, I uninstalled it. Still nothing.

I've scoured all of Northstar GitHub, Wiki & Discord as much as I could for the past 2 hours trying to find a fix & the "most relevant(?)" info I could find was an indication that in release `v1.19.6` the current problem I'm facing was fixed. So I installed v1.19.6 & still nothing.

Validated game files via Steam - still nothing. Used both `-northstar` & `-northstardll` in the launch properties of Steam - still nothing. Opened Nortstar via the manual launcher, Viper & VTOL launchers - still nothing.

I'm unsure whether it's something I haven't checked which could be causing this problem to persist? But if there's any further info which I can provide like logs, a video recording etc. please just indicate & I'll be happy to assist :}

I truly love the Northstar Mod & appreciate the hard work that you all put into it!

### Steps to reproduce

  1. Update to v1.24.4
  2. Launch through any launcher &/or launch properties which opens Northstar normally
  3. Once in the main menu & regardless of the server location, when clicking on "Launch Northstar", a menu with `ConVar ns_is_modded_server` pops up as the guilty party.

### Specifications
  - Northstar version: v1.24.4
  - Platform: Steam

![Screenshot (137)](https://github.com/R2Northstar/Northstar/assets/162905330/dce6a3e2-b30f-4a47-9ea8-9d9e5d50770a)

**Comment by delucax99** [comment]
Thank you!

Just found the problem, it was an older mod "iTz Nao - Remove Locked Multiplayer button" which I now surmise was added as a permanent fix to Northstar.

I appreciate your assistance!

**Comment by GeckoEidechse** [comment]
Great to hear you could resolve it :D
