### ISSUE TITLE
Use a different versioning format

### ISSUE THREAD

**Issue by Jan200101** [R2Northstar/Northstar#653]
Northstar doesn't really make use of any real versioning format with the version just being incremented as is felt.

I am in favort of adopting some versioning schema already applied to the real work like:
- semver
- calver
- WendtVer
- GitVer 
- pragmaticversioning 
- even/odd versioning ([SDL](https://wiki.libsdl.org/SDL2/README/versions))
- ZeroVer

**Comment by GeckoEidechse** [comment]
I think one of the suggestions made somewhere on the Northstar Discord (cannot find it rn) by @F1F7Y was to do like `FEATURE.PATCH` so like e.g. `v82.1`, essentially dropping one version number.

**Comment by Jan200101** [comment]
> I think one of the suggestions [...] was to do like `FEATURE.PATCH` so like e.g. `v82.1` ...

I am in favor of this.

**Comment by GeckoEidechse** [comment]
Maybe to give a bit of backstory of how we ended up with something like `v1.24.7` is that back in the very very early days of Northstar when we released like `v1.4.0` which had a decent refactor at the time, I suggested to @BobTheBob9 just call it a `v2.0.0`, as I was anticipating the scenario we have rn.

At the time they declined saying there's still a few bigger changes in the works that would warrant a 2.0

From there the idea was to have Frontier Defense release or something similar be the 2.0 but as you can obviously tell, that never released (it'll come soon™).

Given that I'm getting back on track, I'm kinda hoping to just get something out that warrants a `2.0` and from there we just push out MAJOR version bumps more liberally quickly going 3.0 -> 4.0 -> ... until version numbers become less relevant to the average player.

**Comment by EM4Volts** [comment]
> Given that I'm getting back on track, I'm kinda hoping to just get something out that warrants a `2.0` and from there we just push out MAJOR version bumps more liberally quickly going 3.0 -> 4.0 -> ... until version numbers become less relevant to the average player.

I dont really think players will care about the version number. Sure announcing a 2.0 would be cool and people would look at it i think ultimately people wont really care.
