### ISSUE TITLE
Unable to change to source command console keybind

### ISSUE THREAD

**Issue by L8zin** [R2Northstar/Northstar#66]
I do not use a US keyboard layout but I'd still like access to the source console in-game. Is there a keybind setting I'm missing or is this something to fix in a future update potentially?

**Comment by GeckoEidechse** [comment]
[This wiki entry](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/commands#opening-the-console) explains how to rebind the key used to open the console.

**Comment by GeckoEidechse** [comment]
Closing this issue for now, please reopen it if the steps described in the wiki did not solve the problem for you.
