### ISSUE TITLE
Engine error (solved)

### ISSUE THREAD

**Issue by ulllupollllo** [R2Northstar/Northstar#68]
![Immagine_2021-12-27_211724](https://user-images.githubusercontent.com/82157501/147504510-6405ae9b-76fa-4422-a2f9-71b180197e84.png)
)

**Comment by abarichello** [comment]
https://github.com/R2Northstar/Northstar/issues/6

**Comment by YungGravyNo** [comment]
same thing happened to me

**Comment by ulllupollllo** [comment]
thx i wasn't logged on ea app

**Comment by MiloAkerman** [comment]
@ulllupollllo you should probably close the issue
