### ISSUE TITLE
R2Northstar Launcher being run,while mod can't be loaded

### ISSUE THREAD

**Issue by Rayxxon** [R2Northstar/Northstar#69]
As described, after clicking the R2Northstar Launcher and it run as expected, the mod options can not be found in the main menu of the game.Guys, need some help over here. Bye the way ,the latest version is installed

**Comment by GeckoEidechse** [comment]
In your Titanfall directory, under `\Titanfall2\R2Northstar\` do you have a file called `enabledmods.json`?
If you do, delete and then start Northstar. Now all mods should be enabled.

(This file is used to tell Northstar to enable/disable mods. Deleting it will cause Northstar to enable all mods again.)

**Comment by Rayxxon** [comment]
Thanks, man.
 i uninstalled the mods and repaired the game. After that,I reinstalled and the mods is loaded normally then

**Comment by Rayxxon** [comment]
I am wondering  that is it possible to make  the maps of Titanfall 1 to be transplanted on Titanfall 2 .And so it is with Titans?
