### ISSUE TITLE
Console doesn't show text on linux

### ISSUE THREAD

**Issue by headassbtw** [R2Northstar/Northstar#7]
this happens regardless of northstar or console, `cl_showpos` and `cl_showfps` don't show either, but if there was anywhere that could shine light on this, it'd be here

![image](https://user-images.githubusercontent.com/16214950/147351417-376c840f-eff9-46bb-9db5-1aac3553d6fb.png)

**Comment by dan26l4** [comment]
What does this mean it’s usable on console

**Comment by timoreo22** [comment]
no we're talking about the in game console (text box where you can run commands)

**Comment by dan26l4** [comment]
> no we're talking about the in game console (text box where you can run commands)

Oh ok

**Comment by abarichello** [comment]
Probably a font error but installing `ttf-ms-fonts` like [this link](https://www.reddit.com/r/archlinux/comments/p5mxjg/font_issue_with_source_engine_games_on_arch_linux/) suggested didn't help

**Comment by GeckoEidechse** [comment]
Installing `lucida` and `arial` seems to fix it according to @abarichello.

For anyone coming across this in the future, check [this entry in the Northstar wiki](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/playing-on-linux#blank-console).
