### ISSUE TITLE
Closed : controller support

### ISSUE THREAD

**Issue by integrated-circuit** [R2Northstar/Northstar#71]
When using DS4Windows, i cannot control my character or go in the menues at all.

**Comment by DxsSucuk** [comment]
Can you use your controller with the Titanfall 2 itself, without Northstar or?

**Comment by AZmaybe9** [comment]
I've found that if I use Steam in Administrator mode, I can use Steam Input for my controller!

**Comment by integrated-circuit** [comment]
edit it is fixed

**Comment by DxsSucuk** [comment]
Please close this Issue then.

**Comment by MiloAkerman** [comment]
Please close the issue with the appropriate button and bot by editing the title
