### ISSUE TITLE
Bot Support

### ISSUE THREAD

**Issue by Lordprime77** [R2Northstar/Northstar#72]
i suck at the game and don't want to try. so can we get bots so i can force them to suffer at the mercy of my scorch.

**Comment by timoreo22** [comment]
Unfortunatly right now bots requires some files only respawn have,
as referenced in #3 pepole are working on seeing how thoses files are made for singleplayer and potentially making them for multiplayer. But that's gonna take time

**Comment by Lordprime77** [comment]
alright, let me know how it goes.

**Comment by taskinoz** [comment]
I'll close this issue now since we don't have to files to make AI work and can't generate them unless we understand the format. Refer to issue #3 for updates
