### ISSUE TITLE
Titanfall 2014 support

### ISSUE THREAD

**Issue by modusc896d352** [R2Northstar/Northstar#73]
so i have a legitimate copy of not only Titanfall 2, but Titanfall as well. i bought them both through EA's Origin service.

**Comment by abarichello** [comment]
I read on the discord that it's being worked on but it will probably be made on another repository since Northstar is Titanfall 2 specific

**Comment by modusc896d352** [comment]
alright.

**Comment by BobTheBob9** [comment]
Titanfall 1 isn't planned to be supported, it doesn't include a server.dll like Titanfall 2 does for singleplayer, so method like what we do for Northstar isn't possible

**Comment by Rayxxon** [comment]
I am wondering that is it possible to make the maps of Titanfall 1 to be transplanted on Titanfall 2 .And so it is with Titans?

**Comment by manotroll** [comment]
would it not be possible to intercept the connection from tf 1 and thus run with the server from 2 or are they very different?

**Comment by GeckoEidechse** [comment]
For TF1, the Titanfall Online remake (till in private development) is probably your best bet.

Regarding making TF1 client communicate with TF2, TFO is basically Titanfall 1.2 and even there the consensus seems to be that it's too much effort to get Titanfall 1 client to talk to TFO. So it it's likely infeasible :/

**Comment by manotroll** [comment]
here the client is not opening someone already did the test?
