### ISSUE TITLE
failure to authenticate?

### ISSUE THREAD

**Issue by lebronjames69** [R2Northstar/Northstar#78]
when i attempt to connect to the multiplayer it says that there was a failure to authenticate. i was able to play for like 4 hours without issue before this happened.

**Comment by lebronjames69** [comment]
specifically says "disconnect. authentication failed"

**Comment by Niconami** [comment]
This issue is effecting everyone check up on #announcements on discord for updates about this stuff

**Comment by lebronjames69** [comment]
thanks man

**Comment by lebronjames69** [comment]
> 

could i get an invite? the link on here doesnt work.

**Comment by Niconami** [comment]
https://discord.gg/r2northstar
