### ISSUE TITLE
Lobby is full when one player joins

### ISSUE THREAD

**Issue by wolf109909** [R2Northstar/Northstar#8]
playlist private_match  lobby has 16slots but others fail to join with error server full. after one match of any mode, the lobby can be joined.

**Comment by bxrdonut** [comment]
same here idk whats happening

**Comment by H000man** [comment]
well is it gonna be fixed or what can i do now

**Comment by MiloAkerman** [comment]
> well is it gonna be fixed or what can i do now

Well, what's your issue and specs? We still need info to fix this.
