### ISSUE TITLE
[Feature Request] Automatic updates

### ISSUE THREAD

**Issue by hrog-zip** [R2Northstar/Northstar#80]
It would be so nice to have a small notification in the launcher about new version and have it automatically update if user willing to.

**Comment by Alystrasz** [comment]
This is being discussed on https://github.com/R2Northstar/NorthstarLauncher/issues/2

**Comment by abarichello** [comment]
The launcher already notifies players of a new update: 
https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDedicatedTest/scriptmainmenupromos.cpp
This file overwrites the announcement boxes that show up on the main menu
