### ISSUE TITLE
Disconnect. Authentication failed

### ISSUE THREAD

**Issue by IsaackCock** [R2Northstar/Northstar#82]
I cannot solve this problem when I try to log into the servers, it throws me into the main menu. I tried to update the launcher, reinstall the game, turn off the brandmair, change the ip. But all to no avail. The command console report this error 
 [error] Failed reading masterserver authentication response: encountred parse error " The document is empty"
 I apologize in advance if this problem can be easily solved, but I do not understand what I need to do.

**Comment by abarichello** [comment]
Masterserver is having some issues right now, check the discord for announcements

**Comment by abarichello** [comment]
Linking #78

**Comment by IsaackCock** [comment]
> Ссылка [# 78](https://github.com/R2Northstar/Northstar/issues/78)

Thank you
