### ISSUE TITLE
[Feature request] Could the modders now potentially fix Titanfall 2 not starting in Full Screen, like almost on every occassion?

### ISSUE THREAD

**Issue by Doomestos** [R2Northstar/Northstar#84]
It is really just a minor complaint, but it always bugged me how Titanfall 2 won't just start in full screen even if it is brute forced through config file or settings in general and it happens to me on various devices and in almost 100% cases of launching it. Now that Northstar gave us access to Titanfall 2's core, could someone have a look at it and finally fix it?

**Comment by SeamusMullan** [comment]
This is possible now!
1. go into your Titanfall 2 install folder 
2. open the `ns_startup_args.txt` file, 
3. add a new line with:
`-noborder`
4. Save and close, restart in fullscreen borderless!

**Comment by Doomestos** [comment]
> 3\. -noborder

Oh man, thank you!

**Comment by abarichello** [comment]
I also had this error so I added this entry to the wiki: https://github.com/R2Northstar/NorthstarWiki/pull/2

**Comment by GeckoEidechse** [comment]
On a side note, pressing `ALT+ENTER` toggles the game between windowed and full screen mode (except when pressing them on loading screens for some reason).
