### ISSUE TITLE
Almost every server in the server browser shows the game mode "Private Match Beta"

### ISSUE THREAD

**Issue by AlanRostem** [R2Northstar/Northstar#87]
The game mode filter in the server browser is completely useless since almost every server has the game mode "Private Match Beta". This makes sense since the game is hosted that way, but since it shows up like that it is very misleading and difficult to find a server with the desired game mode
![image](https://user-images.githubusercontent.com/42648988/147790220-a447671a-8f89-4f23-8bc5-ae4d759c1f8e.png)

**Comment by F1F7Y** [comment]
Default gamemode for servers is "Private match", not many people change it
In reality it's just a Lobby
Also all of those servers have 0 players suggesting no-one started a game yet so the gamemode isn't updated yet
