### ISSUE TITLE
Boosts not functioning as expected (compared to vanilla tf|2)

### ISSUE THREAD

**Issue by IJARika** [R2Northstar/Northstar#88]
In vanilla boosts act as follows:
-stackable (you can hold more than one)
-retained on death
-dice roll doesn't give titan related boosts in modes such as pvp and live fire

In northstar the three listed functions are different:
-they do not stack (as a side effect you only get one tick from boosts)
-the single boost you are holding on death will be reset
-dice roll will give titan batteries and anti titan turret in pvp/live fire modes

These might have been intentional changes, if so please clarify.

**Comment by abarichello** [comment]
Northstar aims for parity with vanilla servers so these were probably not intentional

**Comment by abarichello** [comment]
Linking https://github.com/R2Northstar/NorthstarMods/pull/68

**Comment by IJARika** [comment]
Point three and the second part of point one still persist:
-dice roll will give titan batteries and anti titan turret in pvp/live fire modes
-ticks only give one tick

**Comment by connieprice** [comment]
I know how to fix both of these, once I'm back at a PC I can write another PR

**Comment by connieprice** [comment]
Both of these should be fixed in PR R2Northstar/NorthstarMods#71
