### ISSUE TITLE
Distributed packages missing licenses of included open source software

### ISSUE THREAD

**Issue by JJRcop** [R2Northstar/Northstar#89]
Much of the software libraries used in the NorthstarLauncher use open source software licenses which require you to include the license of the library in any distribution of software which uses the library.

The distributed packages lack these licenses entirely and might break their terms by failing to include them in any form.

I will list some examples with excerpts:

## **MinHook**

>   2. Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

https://github.com/R2Northstar/NorthstarLauncher/blob/f341986b591cee533994597de418df1752ad5e97/NorthstarDedicatedTest/include/MinHook.h#L12-L14

## **OpenSSL**

>  4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:
      (a) You must give any other recipients of the Work or
        Derivative Works a copy of this License;

https://github.com/R2Northstar/NorthstarLauncher/blob/f341986b591cee533994597de418df1752ad5e97/NorthstarDedicatedTest/include/openssl/conf.h#L7-L10

## **MIT Licensed software**

Currently used for all Northstar projects, most of the other software is licensed under this

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

* **RapidJSON**

https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDedicatedTest/include/rapidjson/rapidjson.h#L8

* **libcurl** *(Modified MIT license, but close enough)*

https://github.com/R2Northstar/NorthstarLauncher/blob/f341986b591cee533994597de418df1752ad5e97/NorthstarDedicatedTest/include/libcurl/include/curl/curl.h#L14

* **spdlog**

https://github.com/R2Northstar/NorthstarLauncher/blob/f341986b591cee533994597de418df1752ad5e97/NorthstarDedicatedTest/include/spdlog/spdlog.h#L2

----------------

These licenses are of course included or linked to in the GitHub repos, but are *__NOT__* in the zip archives available from the [releases page](https://github.com/R2Northstar/Northstar/releases) of this repo.

In order to not violate the open source licenses of these libraries, a file should be included in all published archives of this project attributing the licenses of these libraries.

I am not a lawyer and this is not professional legal advice, just an everyman's interpretation of the referenced notices.

**Comment by abarichello** [comment]
https://github.com/R2Northstar/NorthstarLauncher/pull/37
