### ISSUE TITLE
is this possible to work on an xbox one s as i really wanna continue my fight for the frontier 

### ISSUE THREAD

**Issue by dan26l4** [R2Northstar/Northstar#9]

**Comment by timoreo22** [comment]
Unfortunately it seems quite impossible it would require loading a custom game or modifying the game's files.... both are impossible right now as far as i know

**Comment by falconnor4** [comment]
If i can pitch in: titanfall 2 is not a powerhouse of a game and there is controller support via steam. you could possibly find a controller only server and play that way.

**Comment by timoreo22** [comment]
i think their problem is the lack of pc powerful enough

**Comment by dan26l4** [comment]
> If i can pitch in: titanfall 2 is not a powerhouse of a game and there is controller support via steam. you could possibly find a controller only server and play that way.

Yeah I don’t have a pc or steam account I was wondering if this software can be installed and used on a Xbox one s

**Comment by georgewoodall82** [comment]
Maybe you could through the xbox one developer mode, but it costs money.

**Comment by georgewoodall82** [comment]
> Maybe you could through the xbox one developer mode, but it costs money.

Actually i'm not sure if it costs money I haven't used a console in a while

**Comment by BobTheBob9** [comment]
i'm not personally aware of a way to load this on console, there's theoretical ways to get consoles to connect to unmodded custom servers, but in terms of loading the full mod, i don't think it'll be possible
