### ISSUE TITLE
Failed reading masterserver authentication response error "The document is empty."

### ISSUE THREAD

**Issue by zeroshikiry** [R2Northstar/Northstar#91]
The following error will be printed out and the server will display the following message on the browser

[05:21:36] [error] Failed reading masterserver authentication response: encountered parse error "The document is empty."

This problem has been occurring since the master server went down the other day.
I have updated my R2northstar version to v1.3, but the problem persists.
In case you are wondering, I was able to start the server successfully in v1.1 and v1.2.
I have not changed the port settings since v1.2.

**Comment by BulletMemes** [comment]
![image](https://user-images.githubusercontent.com/22633480/147816730-6d810943-a997-4346-9086-a3c2c945926f.png)
This is why. Just gotta be patient and let your dns servers propagate to the new ip.

**Comment by zeroshikiry** [comment]
No authentication errors have occurred in the lobby.
This indicates that the DNS servers in my region have been updated successfully.
Furthermore, when I start it as a client, it is authenticated successfully.

[2022-01-01 00:51:58.760] [info] Trying to authenticate with northstar masterserver for user 2320737386
[2022-01-01 00:52:01.253] [info] Northstar origin authentication completed successfully!

**Comment by zeroshikiry** [comment]
After repeated troubleshooting, a Provisional solutionwas found.

Provisional solution:
Do not allow IPv6 or IPoE networks to coexist on the PC hosting the server.

Work-around:
1. Enable the PPPoE pass-through setting on the main router.
2. Connect the sub-router to the main router and configure the PPPoE connection settings on the sub-router.
3. Disable IPv6-related settings on the sub router (IPv6 pass-through, etc.)
4.Connect your PC to the sub-router's network only when hosting a server.

Details:
Basically, IPSs that provide IPoE do not support specific port opening.
(At least, my IPS can't open the ports required by R2Northstar.)
Therefore, my PC had IPoE and PPPoE networks coexisting.
Before the master server failed, I was able to communicate with the master server even in my IPoE and PPPoE coexistence environment.
But, current master servers seem to prioritize communication over IPv6 or IPoE networks. 
My guess is that this is because Cloudflare supports IPv6, so if the host PC has an IPv6 route, it will prioritize that route.

Request:
If possible, Please stop IPv6 access to the master server altogether.
I'm not sure, but since the previous master server was fine, I think it's likely that something related to IPv6 is in the way.
