### ISSUE TITLE
"Connection to server timed out"

### ISSUE THREAD

**Issue by Twelch115** [R2Northstar/Northstar#94]
Hi, whenever i try to join a server i'm booted back to the menu and i get this error message:
![image](https://user-images.githubusercontent.com/91126396/147825646-90afb6a2-324c-4b6c-9e36-2b28802504cc.png)
Anyone know why this is happening and how i can fix it? 
Cheers

**Comment by MiloAkerman** [comment]
Duplicate of #78. Server issues.
