### ISSUE TITLE
Alt-Tabbing Out Of Fullscreen Game Scrambles Desktop

### ISSUE THREAD

**Issue by MiloAkerman** [R2Northstar/Northstar#96]
I have no idea how this is even possible but launching with `-fullscreen` in the startup args and then alt-tabbing out of the game moves all the icons in my desktop around. Launching the game in fullscreen might also do this, but I am unable to confirm since I have to alt-tab to check.

To repoduce:
- Make Northstar shortcut in Desktop (havent tested by launching exe directly)
- add `-fullscreen` to startup args
- Launch game and press Alt + Tab to switch to another window

**Comment by RaidMax** [comment]
Make sure your ingame resolution and refresh rate mirrors your desktop resolution. Differing resolutions/ refresh rate between desktop (WDM) and the game will cause renegotiating the display parameters on your GPU/monitor when changing focus (alt tab). This used to be a common issue for games on older windows versions where the desktop would get stuck at the game resolution and reorient the icons to fit.

**Comment by MiloAkerman** [comment]
My game resolution is 720p while my desktop resolution is 1080p. However, the game doesn't allowed me to change it at all, as the resolution button is greyed out.

**Comment by GeckoEidechse** [comment]
Can you change the resolution in vanilla?
If so change it there, save it, then check on Northstar.

If not, try going to `Documents\Respawn\Titanfall2\local\` and in `videoconfig.txt` editing `setting.defaultres` and `setting.defaultresheight` to that of your monitor.
