### ISSUE TITLE
Campaign is unable to be loaded

### ISSUE THREAD

**Issue by teamkill3d** [R2Northstar/Northstar#99]
Whenever starting a new game in the singleplayer mode, the tutorial level never ends up finishing loading, and the game softlocks on the beginning loading screen. 

The console report before the game ends up softlocking reads: [23:17:12] [info] [UI SCRIPT] UICodeCallback_UpdateLoadingLevelName: sp_training

(The game is being ran on a 2.5 inch SSD)

**Comment by abarichello** [comment]
Northstar doesn't work with singleplayer for now, launch using the Vanilla executable.
We should probably add this to the docs.

**Comment by GeckoEidechse** [comment]
I added a [note to the FAQ in the Wiki](https://r2northstar.gitbook.io/r2northstar-wiki/faq#q-can-i-use-northstar-to-play-singleplayer) for now [via this commit](https://github.com/R2Northstar/NorthstarWiki/commit/88261c9bc9277693a789dd2fc613d433c762597e).

**Comment by abarichello** [comment]
Thanks

**Comment by zbot473** [comment]
I think it's worth having this up as a tracking issue for singleplayer.

I believe this is a regression from builds around July, because we've been using that to test navmeshes in singleplayer.

**Comment by GeckoEidechse** [comment]
Huh I missed out on that, haha.

@BobTheBob9 keep issue open and use it to track Singleplay/Co-op progress?

**Comment by abarichello** [comment]
> I think it's worth having this up as a tracking issue for singleplayer.
> 
> I believe this is a regression from builds around July, because we've been using that to test navmeshes in singleplayer.

I see, I tought that breaking single player was required for northstar to work
